In [1]:
%load_ext autoreload
%autoreload 2

# dual coding
## circular directrix

In [2]:
import ggblab

In [3]:
from ggblab.utils import flatten

In [4]:
%ggblab api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

In [54]:
%%ggb 
# a = Slider[-3, 3]
# b = Slider[-3, 3]
# c = Slider[-3, 3]
# d = Slider[-3, 3]
a = Slider[0, 10]
# f = Slider[-3, 3]
# a = 1
# c = 1
# f = 1
a = 1

['a', 'a']

In [55]:
%%ggb
F_1 = Point(xAxis)
F_2 = Point(xAxis)

['F_1', 'F_2']

In [56]:
%%ggb
# (-d, 0)
# c_1 = Circle(F_2, a)
c_2 = Circle(F_2, 2a)

['c_1', 'c_2']

In [57]:
%%ggb
P = Point(c_2)
Ray(F_2, P)

['P', 'f']

In [62]:
%%ggb
Ray(F_1, P)

['g']

In [63]:
%%ggb
l = PerpendicularBisector(F_1,P)

['l']

In [68]:
%%ggb
P' = Intersect(f, l)
Segment(F_1, P')

["P'", 'h']

In [61]:
%%ggblab
# Point(xAxis)
Circle(F_1, B)
Intersect(_, xAxis)

['C', 'c', 'D', 'E']

In [72]:
%%ggb
l1 = {Intersect(xAxis, c_2)}
E = l1(1)
F = l1(2)

['l1', 'E', 'F']

In [81]:
%%ggb
O = Midpoint(F_1, F_2)
A = Midpoint(F_1, F)
c = Circle(O, A)
l3 = {Intersect(c, xAxis)}
C = l3(1)

['O', 'A', 'c', 'l3', 'C']

In [75]:
%%ggb
Circle(F_1, a)
Circle(F_2, a)
{Intersect(__, _)}

['d', 'e', 'l2']

In [79]:
%%ggb
B = l2(2)
D = l2(1)

['B', 'D']

In [71]:
%%ggb
a x^2 + b x y + c y^2 + d x + e y + f = 0

Parsed instance=None cmds=['a x^2 + b x y + c y^2 + d x + e y + f = 0']

['eq1']

In [89]:
%%ggb
k = Circle(O, F_1)
i = PerpendicularLine(O, xAxis)
l4 = {Intersect(k, i)}
G = l4(1)
H = l4(2)
Midpoint(O, G)

['k', 'i', 'l4', 'G', 'H', 'I']

In [92]:
%%ggb
l5 = {Intersect(c, i)}
l5(1)
l5(2)

['l5', 'J', 'K']

In [94]:
%%ggb
Midpoint(G, J)

['L']

In [98]:
%%ggb
j = Line(G, l)
l6 = {Intersect(j, c)}
M = l6(1)
N = l6(2)

['j', 'l6', 'M', 'N']

In [99]:
%%ggb
Translate(P', Vector(G, N))

["P''"]

In [101]:
%%ggb
PerpendicularBisector(G, N)

['m']

In [102]:
%ggb Ray(O, N)

['n']

In [108]:
%%ggb
r = Segment(Q, G)

['r']

In [105]:
%%ggb 
Q = Intersect(m, n)

['Q']

In [109]:
%%ggb
Translate(G, Vector(G, N))

["G'"]

In [110]:
%%ggb
Vector(G, G')
Vector(P', P'')

['u', 'v']

In [72]:
from sympy import Matrix, cos, sin, symbols, pi

In [124]:
theta, dx, dy, sx, sy = symbols('theta dx dy sx sy')
a, b, c, d, e, f = symbols('a b c d e f')
x, y, z = symbols('x y z')

In [107]:
m1 = Matrix([[a, b/2, d/2], [b/2, c, e/2], [d/2, e/2, f]])
m1

Matrix([
[  a, b/2, d/2],
[b/2,   c, e/2],
[d/2, e/2,   f]])

In [125]:
m3 = Matrix([[x, y, 1]])

In [130]:
expr = (m3 * m1 * m3.T)
expr.expand()

Matrix([[a*x**2 + b*x*y + c*y**2 + d*x + e*y + f]])

In [108]:
m2 = m1[0:2, 0:2]
m2

Matrix([
[  a, b/2],
[b/2,   c]])

In [109]:
%%ggb
m1 = {m1}
m2 = {m2}

Parsed instance=None cmds=['m1 = {{a,b/2,d/2},{b/2,c,e/2},{d/2,e/2,f}}', 'm2 = {{a,b/2},{b/2,c}}']

['m1', 'm2']

In [115]:
rhs = -(m1.det()/m2.det()).simplify()

In [116]:
%%ggb
{rhs}

Parsed instance=None cmds=['-(4*a*c*f - a*e**2 - b**2*f + b*d*e - c*d**2)/(4*a*c - b**2)']

['k']

In [120]:
sma = (rhs / e1[0][0]).simplify()
smi = (rhs / e1[1][0]).simplify()

In [121]:
sma, smi

(2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c - sqrt(a**2 - 2*a*c + b**2 + c**2))),
 2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c + sqrt(a**2 - 2*a*c + b**2 + c**2))))

In [122]:
%%ggb
{sma}
{smi}

Parsed instance=None cmds=['2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c - sqrt(a**2 - 2*a*c + b**2 + c**2)))', '2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c + sqrt(a**2 - 2*a*c + b**2 + c**2)))']

['j', 'l']

In [76]:
m1.eigenvals()

{a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2: 1,
 a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2: 1}

In [77]:
e1 = m1.eigenvects()
e1

[(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2,
  1,
  [Matrix([
   [-2*c/b + 2*(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b],
   [                                                            1]])]),
 (a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2,
  1,
  [Matrix([
   [-2*c/b + 2*(a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b],
   [                                                            1]])])]

In [78]:
e11 = e1[0][2][0]

In [79]:
e12 = e1[1][2][0]

In [106]:
%%ggb
{e1[0][0]}
{e1[1][0]}

Parsed instance=None cmds=['a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2', 'a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2']

['h', 'i']

In [80]:
%%ggb
{e1[0][2][0]}
{e1[1][2][0]}

Parsed instance=None cmds=['Vector((-2*c/b + 2*(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b,1))', 'Vector((-2*c/b + 2*(a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b,1))']

['u', 'v']

In [81]:
d = str(m1.det()).replace('**', '^')
d

'a*c - b^2/4'

In [82]:
%%ggb
{d}

Parsed instance=None cmds=['a*c - b^2/4']

['g']

In [45]:
e11 = list(flatten(e11.tolist()))

In [ ]:
 = 0

In [87]:
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, function_exponentiation, implicit_multiplication_application, convert_xor
from sympy import pretty, init_printing

# 1. パースの設定 ( ^ -> ** への変換)
transformations = standard_transformations + (function_exponentiation, implicit_multiplication_application, convert_xor, )

# サンプル式: 2x^2 + 3y*z
expr_str = "a x^2 + b x y + c y^2 + d x + e y + f" 

# パースの実行 (implicit_multiplicationを有効にすると、2xが2*xと認識される)
# 注: transformations="all" を使うとさらに自動化が進む
expr = parse_expr(expr_str, transformations=transformations)

In [88]:
expr

a*x**2 + b*x*y + c*y**2 + d*x + e*y + f

In [90]:
from sympy import solve, nonlinsolve, linsolve, diff

In [102]:
c0 = next(iter(linsolve((diff(expr, x), diff(expr, y)), (x, y))))
c0

((b*e - 2*c*d)/(4*a*c - b**2), (-2*a*e + b*d)/(4*a*c - b**2))

In [103]:
%%ggb
{c0}

Parsed instance=None cmds=['((b*e - 2*c*d)/(4*a*c - b**2), (-2*a*e + b*d)/(4*a*c - b**2))']

['A']

In [111]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [112]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
df["Name", "Type", "Command", "Value"]

shape: (47, 4)
┌──────┬─────────┬───────────────────────────────┬─────────────────────────────────┐
│ Name ┆ Type    ┆ Command                       ┆ Value                           │
│ ---  ┆ ---     ┆ ---                           ┆ ---                             │
│ str  ┆ str     ┆ str                           ┆ str                             │
╞══════╪═════════╪═══════════════════════════════╪═════════════════════════════════╡
│ a    ┆ numeric ┆ null                          ┆ a = 1                           │
│ F_1  ┆ point   ┆ Point(xAxis)                  ┆ F_1 = (0.1845633958397, 0)      │
│ F_2  ┆ point   ┆ Point(xAxis)                  ┆ F_2 = (-0.8678668950195, 0)     │
│ c_2  ┆ circle  ┆ Circle(F_2, 2a)               ┆ c_2: (x + 0.8678668950195)² + … │
│ P    ┆ point   ┆ Point(c_2)                    ┆ P = (0.0580874837122, 1.772740… │
│ f    ┆ ray     ┆ Ray(F_2, P)                   ┆ f: -1.7727403894839x + 0.92595… │
│ g    ┆ ray     ┆ Ray(F_1, P)                   ┆ g: -1.7727403894839x - 0.12647… │
│ l    ┆ line    ┆ PerpendicularBisector(F_1, P) ┆ l: 0.1264759121276x - 1.772740… │
│ P'   ┆ point   ┆ Intersect(f, l)               ┆ P' = (-0.4252584354044, 0.8473… │
│ h    ┆ segment ┆ Segment(F_1, P')              ┆ h = 1.0439951043348             │
│ l1   ┆ list    ┆ {Intersect(c_2, xAxis)}       ┆ l1 = {(-2.8678668950195, 0), (… │
│ E    ┆ point   ┆ l1(1)                         ┆ E = (-2.8678668950195, 0)       │
│ F    ┆ point   ┆ l1(2)                         ┆ F = (1.1321331049805, 0)        │
│ O    ┆ point   ┆ Midpoint(F_1, F_2)            ┆ O = (-0.3416517495899, 0)       │
│ A    ┆ point   ┆ Midpoint(F_1, F)              ┆ A = (0.6583482504101, 0)        │
│ c    ┆ circle  ┆ Circle(O, A)                  ┆ c: (x + 0.3416517495899)² + y²… │
│ d    ┆ circle  ┆ Circle(F_1, a)                ┆ d: (x - 0.1845633958397)² + y²… │
│ e    ┆ circle  ┆ Circle(F_2, a)                ┆ e: (x + 0.8678668950195)² + y²… │
│ l2   ┆ list    ┆ {Intersect(d, e)}             ┆ l2 = {(-0.3416517495899, -0.85… │
│ B    ┆ point   ┆ l2(2)                         ┆ B = (-0.3416517495899, 0.85035… │
│ D    ┆ point   ┆ l2(1)                         ┆ D = (-0.3416517495899, -0.8503… │
│ l3   ┆ list    ┆ {Intersect(c, xAxis)}         ┆ l3 = {(-1.3416517495899, 0), (… │
│ C    ┆ point   ┆ l3(1)                         ┆ C = (-1.3416517495899, 0)       │
│ k    ┆ circle  ┆ Circle(O, F_1)                ┆ k: (x + 0.3416517495899)² + y²… │
│ i    ┆ line    ┆ PerpendicularLine(O, xAxis)   ┆ i: x = -0.3416517495899         │
│ l4   ┆ list    ┆ {Intersect(k, i)}             ┆ l4 = {(-0.3416517495899, -0.52… │
│ G    ┆ point   ┆ l4(1)                         ┆ G = (-0.3416517495899, -0.5262… │
│ H    ┆ point   ┆ l4(2)                         ┆ H = (-0.3416517495899, 0.52621… │
│ I    ┆ point   ┆ Midpoint(O, G)                ┆ I = (-0.3416517495899, -0.2631… │
│ l5   ┆ list    ┆ {Intersect(c, i)}             ┆ l5 = {(-0.3416517495899, -1), … │
│ J    ┆ point   ┆ l5(1)                         ┆ J = (-0.3416517495899, -1)      │
│ K    ┆ point   ┆ l5(2)                         ┆ K = (-0.3416517495899, 1)       │
│ L    ┆ point   ┆ Midpoint(G, J)                ┆ L = (-0.3416517495899, -0.7631… │
│ p    ┆ ellipse ┆ Ellipse(O, G, L)              ┆ p: 4x² + 2.892390482882y² + 2.… │
│ j    ┆ line    ┆ Line(G, l)                    ┆ j: 0.1264759121276x - 1.772740… │
│ l6   ┆ list    ┆ {Intersect(c, j)}             ┆ l6 = {(0.5447184451521, -0.462… │
│ M    ┆ point   ┆ l6(1)                         ┆ M = (0.5447184451521, -0.46297… │
│ N    ┆ point   ┆ l6(2)                         ┆ N = (-1.153316710495, -0.58412… │
│ P''  ┆ point   ┆ Translate(P', Vector(G, N))   ┆ P'' = (-1.2369233963096, 0.789… │
│ m    ┆ line    ┆ PerpendicularBisector(G, N)   ┆ m: 0.8116649609051x + 0.057908… │
│ n    ┆ ray     ┆ Ray(O, N)                     ┆ n: 0.584123267161x - 0.8116649… │
│ Q    ┆ point   ┆ Intersect(m, n)               ┆ Q = (-0.7653388723624, -0.3049… │
│ r    ┆ segment ┆ Segment(Q, G)                 ┆ r = 0.4780024478326             │
│ G'   ┆ point   ┆ Translate(G, Vector(G, N))    ┆ G' = (-1.153316710495, -0.5841… │
│ u    ┆ vector  ┆ Vector(G, G')                 ┆ u = (-0.8116649609051, -0.0579… │
│ v    ┆ vector  ┆ Vector(P', P'')               ┆ v = (-0.8116649609051, -0.0579… │
│ q    ┆ ellipse ┆ Ellipse(F_2, F_1, P')         ┆ q: 11.5695619315279x² + 16y² +… │
└──────┴─────────┴───────────────────────────────┴─────────────────────────────────┘

In [113]:
from ggblab_extra.sympy import Object2D, Object3D
from ggblab_extra.sympy import attach_object2d, attach_object3d, enumerate_plane_members

In [114]:
df2 = attach_object2d(df)

In [135]:
df2["Name", "Type", "object2d"]

shape: (47, 3)
┌──────┬─────────┬─────────────────────────────────┐
│ Name ┆ Type    ┆ object2d                        │
│ ---  ┆ ---     ┆ ---                             │
│ str  ┆ str     ┆ object                          │
╞══════╪═════════╪═════════════════════════════════╡
│ a    ┆ numeric ┆ null                            │
│ F_1  ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ F_2  ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ c_2  ┆ circle  ┆ Object2D(kind='circle', obj=No… │
│ P    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ f    ┆ ray     ┆ Object2D(kind='ray', obj=Ray2D… │
│ g    ┆ ray     ┆ Object2D(kind='ray', obj=Ray2D… │
│ l    ┆ line    ┆ Object2D(kind='line', obj=Line… │
│ P'   ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ h    ┆ segment ┆ Object2D(kind='segment', obj=S… │
│ l1   ┆ list    ┆ null                            │
│ E    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ F    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ O    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ A    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ c    ┆ circle  ┆ Object2D(kind='circle', obj=No… │
│ d    ┆ circle  ┆ Object2D(kind='circle', obj=No… │
│ e    ┆ circle  ┆ Object2D(kind='circle', obj=No… │
│ l2   ┆ list    ┆ null                            │
│ B    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ D    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ l3   ┆ list    ┆ null                            │
│ C    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ k    ┆ circle  ┆ Object2D(kind='circle', obj=No… │
│ i    ┆ line    ┆ Object2D(kind='line', obj=Line… │
│ l4   ┆ list    ┆ null                            │
│ G    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ H    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ I    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ l5   ┆ list    ┆ null                            │
│ J    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ K    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ L    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ p    ┆ ellipse ┆ Object2D(kind=None, obj=None, … │
│ j    ┆ line    ┆ Object2D(kind='line', obj=Line… │
│ l6   ┆ list    ┆ null                            │
│ M    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ N    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ P''  ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ m    ┆ line    ┆ Object2D(kind='line', obj=Line… │
│ n    ┆ ray     ┆ Object2D(kind='ray', obj=Ray2D… │
│ Q    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ r    ┆ segment ┆ Object2D(kind='segment', obj=S… │
│ G'   ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ u    ┆ vector  ┆ Object2D(kind='point', obj=Poi… │
│ v    ┆ vector  ┆ Object2D(kind='point', obj=Poi… │
│ q    ┆ ellipse ┆ Object2D(kind=None, obj=None, … │
└──────┴─────────┴─────────────────────────────────┘

In [139]:
import polars as pl

In [146]:
p_a = df2.filter(pl.col("Name") == "A")["object2d"].item().obj

In [147]:
p_o = df2.filter(pl.col("Name") == "O")["object2d"].item().obj

In [148]:
p_f1 = df2.filter(pl.col("Name") == "F_1")["object2d"].item().obj

In [149]:
p_a, p_o, p_f1

(Point2D(6583482504101/10000000000000, 0),
 Point2D(-3416517495899/10000000000000, 0),
 Point2D(1845633958397/10000000000000, 0))

In [150]:
(p_o.distance(p_f1) / p_o.distance(p_a)).evalf()

0.526215145429600

In [151]:
p_i = df2.filter(pl.col("Name") == "I")["object2d"].item().obj

In [152]:
p_l = df2.filter(pl.col("Name") == "L")["object2d"].item().obj

In [153]:
p_g = df2.filter(pl.col("Name") == "G")["object2d"].item().obj

In [154]:
(p_i.distance(p_g) / p_i.distance(p_l)).evalf()

0.526215145429600

In [155]:
p_i.distance(p_l)

1/2