In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import ggblab

In [3]:
%ggb api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

In [168]:
c = ggb.file.load('ellipse by newton.ggb')

In [130]:
await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [131]:
await ggb.init()

In [132]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [133]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
# df = await ConstructionIO.initialize_dataframe(ggb, file='ellipse by newton.ggb')
df

shape: (114, 10)
┌──────────┬────────┬──────────────┬──────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name   ┆ Type         ┆ Command      ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---    ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str    ┆ str          ┆ str          ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪════════╪══════════════╪══════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 1        ┆ F'_2   ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ false      ┆ true      ┆ false     │
│ 2        ┆ F_1    ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 3        ┆ V      ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 4        ┆ c      ┆ hyperbola    ┆ Hyperbola(F' ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ _2, F_1, V)  ┆   ┆       ┆            ┆           ┆           │
│ 5        ┆ F_2    ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 6        ┆ e      ┆ ellipse      ┆ Ellipse(F_1, ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_2, V)      ┆   ┆       ┆            ┆           ┆           │
│ 7        ┆ P_3    ┆ point        ┆ Point(c)     ┆ … ┆ 9     ┆ false      ┆ true      ┆ false     │
│ 8        ┆ i      ┆ ray          ┆ Ray(F_1,     ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_3)         ┆   ┆       ┆            ┆           ┆           │
│ 9        ┆ O'     ┆ point        ┆ Midpoint(F'_ ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ 2, F_1)      ┆   ┆       ┆            ┆           ┆           │
│ 10       ┆ j      ┆ line         ┆ Asymptote(c) ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 11       ┆ k      ┆ line         ┆ Asymptote(c) ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 12       ┆ m      ┆ line         ┆ Tangent(P_3, ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ c)           ┆   ┆       ┆            ┆           ┆           │
│ 13       ┆ n      ┆ line         ┆ Line(O', m)  ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│ 14       ┆ M      ┆ point        ┆ Intersect(n, ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│          ┆        ┆              ┆ i)           ┆   ┆       ┆            ┆           ┆           │
│ 15       ┆ O      ┆ point        ┆ Midpoint(F_1 ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ , F_2)       ┆   ┆       ┆            ┆           ┆           │
│ 16       ┆ g      ┆ circle       ┆ Circle(O, V) ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│ 17       ┆ h      ┆ circle       ┆ Circle(V,    ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1)         ┆   ┆       ┆            ┆           ┆           │
│ 18       ┆ D      ┆ point        ┆ Intersect(h, ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ xAxis)       ┆   ┆       ┆            ┆           ┆           │
│ 19       ┆ I      ┆ point        ┆ Intersect(h, ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ xAxis)       ┆   ┆       ┆            ┆           ┆           │
│ 20       ┆ f      ┆ line         ┆ Perpendicula ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(I,     ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ xAxis)       ┆   ┆       ┆            ┆           ┆           │
│ 21       ┆ d      ┆ parabola     ┆ Parabola(D,  ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ f)           ┆   ┆       ┆            ┆           ┆           │
│ 22       ┆ p      ┆ circle       ┆ Circle(F_2,  ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ I)           ┆   ┆       ┆            ┆           ┆           │
│ 23       ┆ l      ┆ ray          ┆ Ray(F'_2,    ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_3)         ┆   ┆       ┆            ┆           ┆           │
│ 24       ┆ β      ┆ angle        ┆ Angle(m, l)  ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 25       ┆ q      ┆ segment      ┆ Segment(P_3, ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ M)           ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ P_2    ┆ point        ┆ Point(p)     ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 27       ┆ r      ┆ line         ┆ Perpendicula ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ rBisector(F_ ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ 1, P_2…      ┆   ┆       ┆            ┆           ┆           │
│ 28       ┆ s      ┆ ray          ┆ Ray(F_2,     ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_2)         ┆   ┆       ┆            ┆           ┆           │
│ 29       ┆ P'_2   ┆ point        ┆ Intersect(s, ┆ … ┆ 3     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 30       ┆ P'''_2 ┆ point        ┆ Intersect(g, ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 31       ┆ P''_2  ┆ point        ┆ Intersect(g, ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 32       ┆ t      ┆ segment      ┆ Segment(O,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P''_2)       ┆   ┆       ┆            ┆           ┆           │
│ 33       ┆ b      ┆ line         ┆ Line(F_1,    ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2)        ┆   ┆       ┆            ┆           ┆           │
│ 34       ┆ γ      ┆ angle        ┆ Angle(F_2,   ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2, P''_2) ┆   ┆       ┆            ┆           ┆           │
│ 35       ┆ a      ┆ segment      ┆ Segment(O,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'''_2)      ┆   ┆       ┆            ┆           ┆           │
│ 36       ┆ δ      ┆ angle        ┆ Angle(F_1,   ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2,        ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ P'''_2)      ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ f_1    ┆ line         ┆ Line(O, r)   ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│ 38       ┆ O_{4}  ┆ point        ┆ Intersect(f_ ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, b)        ┆   ┆       ┆            ┆           ┆           │
│ 39       ┆ g_1    ┆ segment      ┆ Segment(O_{4 ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ }, P'_2)     ┆   ┆       ┆            ┆           ┆           │
│ 40       ┆ P_1    ┆ point        ┆ Point(d)     ┆ … ┆ 9     ┆ false      ┆ true      ┆ false     │
│ 41       ┆ h_1    ┆ line         ┆ Perpendicula ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(P_1,   ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ f)           ┆   ┆       ┆            ┆           ┆           │
│ 42       ┆ i_1    ┆ ray          ┆ Ray(F_1,     ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_1)         ┆   ┆       ┆            ┆           ┆           │
│ 43       ┆ j_1    ┆ line         ┆ AngleBisecto ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ r(i_1, h_1)  ┆   ┆       ┆            ┆           ┆           │
│ 44       ┆ k_1    ┆ line         ┆ AngleBisecto ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ r(i_1, h_1)  ┆   ┆       ┆            ┆           ┆           │
│ 45       ┆ Q      ┆ point        ┆ Intersect(k_ ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ 1, xAxis)    ┆   ┆       ┆            ┆           ┆           │
│ 46       ┆ R      ┆ point        ┆ Intersect(h_ ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, f)        ┆   ┆       ┆            ┆           ┆           │
│ 47       ┆ q1     ┆ quadrilatera ┆ Polygon(F_1, ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆ l            ┆ P_1, R, Q)   ┆   ┆       ┆            ┆           ┆           │
│ 48       ┆ b_1    ┆ segment      ┆ Segment(F_1, ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_1, q1)     ┆   ┆       ┆            ┆           ┆           │
│ 49       ┆ p_1    ┆ segment      ┆ Segment(P_1, ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ R, q1)       ┆   ┆       ┆            ┆           ┆           │
│ 50       ┆ r_1    ┆ segment      ┆ Segment(R,   ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ Q, q1)       ┆   ┆       ┆            ┆           ┆           │
│ 51       ┆ q_1    ┆ segment      ┆ Segment(Q,   ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1, q1)     ┆   ┆       ┆            ┆           ┆           │
│ 52       ┆ S      ┆ point        ┆ Midpoint(F_1 ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ , R)         ┆   ┆       ┆            ┆           ┆           │
│ 53       ┆ t1     ┆ triangle     ┆ Polygon(F_1, ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ V, S)        ┆   ┆       ┆            ┆           ┆           │
│ 54       ┆ s_1    ┆ segment      ┆ Segment(F_1, ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ V, t1)       ┆   ┆       ┆            ┆           ┆           │
│ 55       ┆ b_2    ┆ segment      ┆ Segment(V,   ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ S, t1)       ┆   ┆       ┆            ┆           ┆           │
│ 56       ┆ c_1    ┆ segment      ┆ Segment(S,   ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1, t1)     ┆   ┆       ┆            ┆           ┆           │
│ 57       ┆ m_1    ┆ line         ┆ Perpendicula ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(P'_2,  ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ f_1)         ┆   ┆       ┆            ┆           ┆           │
│ 58       ┆ T      ┆ point        ┆ Intersect(m_ ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, f_1)      ┆   ┆       ┆            ┆           ┆           │
│ 59       ┆ n_1    ┆ line         ┆ Perpendicula ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(P_3,   ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ n)           ┆   ┆       ┆            ┆           ┆           │
│ 60       ┆ U      ┆ point        ┆ Intersect(n_ ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, n)        ┆   ┆       ┆            ┆           ┆           │
│ 61       ┆ ε      ┆ angle        ┆ Angle(F_1,   ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_1, S)      ┆   ┆       ┆            ┆           ┆           │
│ 62       ┆ d_1    ┆ circle       ┆ Circle(P_1,  ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ R)           ┆   ┆       ┆            ┆           ┆           │
│ 63       ┆ A      ┆ point        ┆ Intersect(d_ ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, h_1)      ┆   ┆       ┆            ┆           ┆           │
│ 64       ┆ B      ┆ point        ┆ Intersect(d_ ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ 1, h_1)      ┆   ┆       ┆            ┆           ┆           │
│ 65       ┆ t_1    ┆ ray          ┆ Ray(P_1, B)  ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│ 66       ┆ a_1    ┆ segment      ┆ Segment(P_1, ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1)         ┆   ┆       ┆            ┆           ┆           │
│ 67       ┆ e_1    ┆ segment      ┆ Segment(B,   ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_1)         ┆   ┆       ┆            ┆           ┆           │
│ 68       ┆ c_2    ┆ circle       ┆ Circle(P_1,  ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ Q)           ┆   ┆       ┆            ┆           ┆           │
│ 69       ┆ C      ┆ point        ┆ Intersect(c_ ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ 2, k_1)      ┆   ┆       ┆            ┆           ┆           │
│ 70       ┆ E      ┆ point        ┆ Intersect(c_ ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ 2, k_1)      ┆   ┆       ┆            ┆           ┆           │
│ 71       ┆ ζ      ┆ angle        ┆ Angle(E,     ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_1, B)      ┆   ┆       ┆            ┆           ┆           │
│ 72       ┆ f_2    ┆ line         ┆ Line(F_1, V) ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│ 73       ┆ g_2    ┆ segment      ┆ Segment(F_2, ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2)        ┆   ┆       ┆            ┆           ┆           │
│ 74       ┆ h_2    ┆ segment      ┆ Segment(P'_2 ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ , F_1)       ┆   ┆       ┆            ┆           ┆           │
│ 75       ┆ η      ┆ angle        ┆ Angle(P'_2,  ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ T, O_{4})    ┆   ┆       ┆            ┆           ┆           │
│ 76       ┆ d_2    ┆ circle       ┆ Circle(P_3,  ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ F'_2)        ┆   ┆       ┆            ┆           ┆           │
│ 77       ┆ F      ┆ point        ┆ Intersect(d_ ┆ … ┆ 5     ┆ false      ┆ true      ┆ true      │
│          ┆        ┆              ┆ 2, m)        ┆   ┆       ┆            ┆           ┆           │
│ 78       ┆ G      ┆ point        ┆ Intersect(d_ ┆ … ┆ 5     ┆ false      ┆ true      ┆ true      │
│          ┆        ┆              ┆ 2, m)        ┆   ┆       ┆            ┆           ┆           │
│ 79       ┆ α      ┆ angle        ┆ Angle(F_1,   ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_3, F)      ┆   ┆       ┆            ┆           ┆           │
│ 80       ┆ H      ┆ point        ┆ Intersect(d_ ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ 2, l)        ┆   ┆       ┆            ┆           ┆           │
│ 81       ┆ J      ┆ point        ┆ Intersect(d_ ┆ … ┆ 5     ┆ false      ┆ true      ┆ true      │
│          ┆        ┆              ┆ 2, l)        ┆   ┆       ┆            ┆           ┆           │
│ 82       ┆ l_1    ┆ ray          ┆ Ray(P_3, J)  ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 83       ┆ i_2    ┆ segment      ┆ Segment(J,   ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_3)         ┆   ┆       ┆            ┆           ┆           │
│ 84       ┆ j_2    ┆ segment      ┆ Segment(P_3, ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1)         ┆   ┆       ┆            ┆           ┆           │
│ 85       ┆ θ      ┆ angle        ┆ Angle(P_3,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ U, M)        ┆   ┆       ┆            ┆           ┆           │
│ 86       ┆ e_2    ┆ circle       ┆ Circle(F'_2, ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ Distance(O', ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ V) *…        ┆   ┆       ┆            ┆           ┆           │
│ 87       ┆ k_2    ┆ circle       ┆ Circle(P_3,  ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1)         ┆   ┆       ┆            ┆           ┆           │
│ 88       ┆ l_2    ┆ line         ┆ Line(F'_2,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ m)           ┆   ┆       ┆            ┆           ┆           │
│ 89       ┆ K      ┆ point        ┆ Intersect(l_ ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ 2, i)        ┆   ┆       ┆            ┆           ┆           │
│ 90       ┆ t2     ┆ triangle     ┆ Polygon(F'_2 ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ , P_3, K)    ┆   ┆       ┆            ┆           ┆           │
│ 91       ┆ k_3    ┆ segment      ┆ Segment(F'_2 ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ , P_3, t2)   ┆   ┆       ┆            ┆           ┆           │
│ 92       ┆ f'_2   ┆ segment      ┆ Segment(P_3, ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ K, t2)       ┆   ┆       ┆            ┆           ┆           │
│ 93       ┆ p_3    ┆ segment      ┆ Segment(K,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ F'_2, t2)    ┆   ┆       ┆            ┆           ┆           │
│ 94       ┆ q2     ┆ quadrilatera ┆ Polygon(O,   ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆ l            ┆ O_{4}, P'_2, ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ P''_2)       ┆   ┆       ┆            ┆           ┆           │
│ 95       ┆ m_2    ┆ segment      ┆ Segment(O,   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ O_{4}, q2)   ┆   ┆       ┆            ┆           ┆           │
│ 96       ┆ n_2    ┆ segment      ┆ Segment(O_{4 ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ }, P'_2, q2) ┆   ┆       ┆            ┆           ┆           │
│ 97       ┆ p_2    ┆ segment      ┆ Segment(P'_2 ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ , P''_2, q2) ┆   ┆       ┆            ┆           ┆           │
│ 98       ┆ q_2    ┆ segment      ┆ Segment(P''_ ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ 2, O, q2)    ┆   ┆       ┆            ┆           ┆           │
│ 99       ┆ ι      ┆ angle        ┆ Angle(F_1,   ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ V, S)        ┆   ┆       ┆            ┆           ┆           │
│ 100      ┆ cv_{1} ┆ vector       ┆ CurvatureVec ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ tor(P_1, d)  ┆   ┆       ┆            ┆           ┆           │

In [72]:
import xml.etree.ElementTree as ET
import xmlschema
import polars as pl
import networkx as nx
from itertools import zip_longest

In [28]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [134]:
p = ConstructionTreeParser(df)
g1 = p.parse()

In [135]:
s1 = nx.descendants(g1, 'd')
s2 = nx.descendants(g1, 'p')
s3 = nx.descendants(g1, 'c')
s4 = nx.descendants(g1, "F'_2")

In [146]:
df.filter(~pl.col("Name").is_in({'d', 'c', "F'_2"} | s1 | s3 | s4))

shape: (45, 10)
┌──────────┬────────┬──────────────┬──────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name   ┆ Type         ┆ Command      ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---    ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str    ┆ str          ┆ str          ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪════════╪══════════════╪══════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 2        ┆ F_1    ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 3        ┆ V      ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 5        ┆ F_2    ┆ point        ┆ Point(xAxis) ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 6        ┆ e      ┆ ellipse      ┆ Ellipse(F_1, ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_2, V)      ┆   ┆       ┆            ┆           ┆           │
│ 15       ┆ O      ┆ point        ┆ Midpoint(F_1 ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ , F_2)       ┆   ┆       ┆            ┆           ┆           │
│ 16       ┆ g      ┆ circle       ┆ Circle(O, V) ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│ 17       ┆ h      ┆ circle       ┆ Circle(V,    ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ F_1)         ┆   ┆       ┆            ┆           ┆           │
│ 18       ┆ D      ┆ point        ┆ Intersect(h, ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ xAxis)       ┆   ┆       ┆            ┆           ┆           │
│ 19       ┆ I      ┆ point        ┆ Intersect(h, ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ xAxis)       ┆   ┆       ┆            ┆           ┆           │
│ 20       ┆ f      ┆ line         ┆ Perpendicula ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(I,     ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ xAxis)       ┆   ┆       ┆            ┆           ┆           │
│ 22       ┆ p      ┆ circle       ┆ Circle(F_2,  ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ I)           ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ P_2    ┆ point        ┆ Point(p)     ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 27       ┆ r      ┆ line         ┆ Perpendicula ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ rBisector(F_ ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ 1, P_2…      ┆   ┆       ┆            ┆           ┆           │
│ 28       ┆ s      ┆ ray          ┆ Ray(F_2,     ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P_2)         ┆   ┆       ┆            ┆           ┆           │
│ 29       ┆ P'_2   ┆ point        ┆ Intersect(s, ┆ … ┆ 3     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 30       ┆ P'''_2 ┆ point        ┆ Intersect(g, ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 31       ┆ P''_2  ┆ point        ┆ Intersect(g, ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 32       ┆ t      ┆ segment      ┆ Segment(O,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P''_2)       ┆   ┆       ┆            ┆           ┆           │
│ 33       ┆ b      ┆ line         ┆ Line(F_1,    ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2)        ┆   ┆       ┆            ┆           ┆           │
│ 34       ┆ γ      ┆ angle        ┆ Angle(F_2,   ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2, P''_2) ┆   ┆       ┆            ┆           ┆           │
│ 35       ┆ a      ┆ segment      ┆ Segment(O,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'''_2)      ┆   ┆       ┆            ┆           ┆           │
│ 36       ┆ δ      ┆ angle        ┆ Angle(F_1,   ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2,        ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ P'''_2)      ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ f_1    ┆ line         ┆ Line(O, r)   ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│ 38       ┆ O_{4}  ┆ point        ┆ Intersect(f_ ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, b)        ┆   ┆       ┆            ┆           ┆           │
│ 39       ┆ g_1    ┆ segment      ┆ Segment(O_{4 ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ }, P'_2)     ┆   ┆       ┆            ┆           ┆           │
│ 57       ┆ m_1    ┆ line         ┆ Perpendicula ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(P'_2,  ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ f_1)         ┆   ┆       ┆            ┆           ┆           │
│ 58       ┆ T      ┆ point        ┆ Intersect(m_ ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ 1, f_1)      ┆   ┆       ┆            ┆           ┆           │
│ 72       ┆ f_2    ┆ line         ┆ Line(F_1, V) ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│ 73       ┆ g_2    ┆ segment      ┆ Segment(F_2, ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2)        ┆   ┆       ┆            ┆           ┆           │
│ 74       ┆ h_2    ┆ segment      ┆ Segment(P'_2 ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ , F_1)       ┆   ┆       ┆            ┆           ┆           │
│ 75       ┆ η      ┆ angle        ┆ Angle(P'_2,  ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ T, O_{4})    ┆   ┆       ┆            ┆           ┆           │
│ 94       ┆ q2     ┆ quadrilatera ┆ Polygon(O,   ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆ l            ┆ O_{4}, P'_2, ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ P''_2)       ┆   ┆       ┆            ┆           ┆           │
│ 95       ┆ m_2    ┆ segment      ┆ Segment(O,   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ O_{4}, q2)   ┆   ┆       ┆            ┆           ┆           │
│ 96       ┆ n_2    ┆ segment      ┆ Segment(O_{4 ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ }, P'_2, q2) ┆   ┆       ┆            ┆           ┆           │
│ 97       ┆ p_2    ┆ segment      ┆ Segment(P'_2 ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ , P''_2, q2) ┆   ┆       ┆            ┆           ┆           │
│ 98       ┆ q_2    ┆ segment      ┆ Segment(P''_ ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ 2, O, q2)    ┆   ┆       ┆            ┆           ┆           │
│ 103      ┆ cv_{2} ┆ vector       ┆ CurvatureVec ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆        ┆              ┆ tor(P'_2, e) ┆   ┆       ┆            ┆           ┆           │
│ 104      ┆ O_2    ┆ point        ┆ Translate(P' ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ _2, Vector(c ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ v_{2} …      ┆   ┆       ┆            ┆           ┆           │
│ 105      ┆ s_2    ┆ circle       ┆ Circle(O_2,  ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'_2)        ┆   ┆       ┆            ┆           ┆           │
│ 109      ┆ a_2    ┆ line         ┆ Perpendicula ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ rLine(P'_2,  ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ r)           ┆   ┆       ┆            ┆           ┆           │
│ 110      ┆ cv     ┆ vector       ┆ CurvatureVec ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│          ┆        ┆              ┆ tor(P'_2, e) ┆   ┆       ┆            ┆           ┆           │
│ 111      ┆ L      ┆ point        ┆ Translate(P' ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│          ┆        ┆              ┆ _2,          ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ Vector(cv /  ┆   ┆       ┆            ┆           ┆           │
│          ┆        ┆              ┆ Le…          ┆   ┆       ┆            ┆           ┆           │
│ 112      ┆ f_3    ┆ segment      ┆ Segment(P''' ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ _2, F_1)     ┆   ┆       ┆            ┆           ┆           │
│ 113      ┆ g_3    ┆ segment      ┆ Segment(P''' ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ _2, P_2)     ┆   ┆       ┆            ┆           ┆           │
│ 114      ┆ κ      ┆ angle        ┆ Angle(P''_2, ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆        ┆              ┆ P'''_2, P_2) ┆   ┆       ┆            ┆           ┆           │
└──────────┴────────┴──────────────┴──────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [147]:
cmds = ConstructionIO.commands_for_magic(_.filter(pl.col("Layer").is_in([9, 0, 3, 4])), use_name_equals=True)
print(cmds)

F_1 = Point(xAxis)
V = Point(xAxis)
F_2 = Point(xAxis)
e = Ellipse(F_1, F_2, V)
O = Midpoint(F_1, F_2)
g = Circle(O, V)
h = Circle(V, F_1)
I = Intersect(h, xAxis)
p = Circle(F_2, I)
P_2 = Point(p)
r = PerpendicularBisector(F_1, P_2)
s = Ray(F_2, P_2)
P'_2 = Intersect(s, r)
P'''_2 = Intersect(g, r)
P''_2 = Intersect(g, r)
t = Segment(O, P''_2)
b = Line(F_1, P'_2)
γ = Angle(F_2, P'_2, P''_2)
a = Segment(O, P'''_2)
δ = Angle(F_1, P'_2, P'''_2)
f_1 = Line(O, r)
O_{4} = Intersect(f_1, b)
g_1 = Segment(O_{4}, P'_2)
m_1 = PerpendicularLine(P'_2, f_1)
T = Intersect(m_1, f_1)
g_2 = Segment(F_2, P'_2)
h_2 = Segment(P'_2, F_1)
η = Angle(P'_2, T, O_{4})
q2 = Polygon(O, O_{4}, P'_2, P''_2)
m_2 = Segment(O, O_{4}, q2)
n_2 = Segment(O_{4}, P'_2, q2)
p_2 = Segment(P'_2, P''_2, q2)
q_2 = Segment(P''_2, O, q2)
cv_{2} = CurvatureVector(P'_2, e)
O_2 = Translate(P'_2, Vector(cv_{2} / Length(cv_{2})²))
s_2 = Circle(O_2, P'_2)
f_3 = Segment(P'''_2, F_1)
g_3 = Segment(P'''_2, P_2)
κ = Angle(P''_2, P'''_2, P_2)

In [164]:
_cmds = """#
F_1 = Point(xAxis)
V = Point(xAxis)
F_2 = Point(xAxis)
e = Ellipse(F_1, F_2, V)
O = Midpoint(F_1, F_2)
g = Circle(O, V)
h = Circle(V, F_1)
l0 = {Intersect(h, xAxis)}
I = l0(2)
p = Circle(F_2, I)
P_2 = Point(p)
r = PerpendicularBisector(F_1, P_2)
s = Ray(F_2, P_2)
P'_2 = Intersect(s, r)
l1 = {Intersect(g, r)}
P'''_2 = l1(1)
P''_2 = l1(2)
t = Segment(O, P''_2)
b = Line(F_1, P'_2)
γ = Angle(F_2, P'_2, P''_2)
a = Segment(O, P'''_2)
δ = Angle(F_1, P'_2, P'''_2)
f_1 = Line(O, r)
O_{4} = Intersect(f_1, b)
g_1 = Segment(O_{4}, P'_2)
m_1 = PerpendicularLine(P'_2, f_1)
T = Intersect(m_1, f_1)
g_2 = Segment(F_2, P'_2)
h_2 = Segment(P'_2, F_1)
η = Angle(P'_2, T, O_{4})
q2 = Polygon(O, O_{4}, P'_2, P''_2)
m_2 = Segment(O, O_{4}, q2)
n_2 = Segment(O_{4}, P'_2, q2)
p_2 = Segment(P'_2, P''_2, q2)
q_2 = Segment(P''_2, O, q2)
cv_{2} = CurvatureVector(P'_2, e)
O_2 = Translate(P'_2, Vector(cv_{2} / Length(cv_{2})²))
s_2 = Circle(O_2, P'_2)
f_3 = Segment(P'''_2, F_1)
g_3 = Segment(P'''_2, P_2)
κ = Angle(P''_2, P'''_2, P_2)
#"""

In [165]:
%ggb "{_cmds}"

ggb.command('F_1 = Point(xAxis)') -> 'F_1'
ggb.command('V = Point(xAxis)') -> 'V'
ggb.command('F_2 = Point(xAxis)') -> 'F_2'
ggb.command('e = Ellipse(F_1, F_2, V)') -> 'e'
ggb.command('O = Midpoint(F_1, F_2)') -> 'O'
ggb.command('g = Circle(O, V)') -> 'g'
ggb.command('h = Circle(V, F_1)') -> 'h'
ggb.command('l0 = {Intersect(h, xAxis)}') -> 'l0'
ggb.command('I = l0(2)') -> 'I'
ggb.command('p = Circle(F_2, I)') -> 'p'
ggb.command('P_2 = Point(p)') -> 'P_2'
ggb.command('r = PerpendicularBisector(F_1, P_2)') -> 'r'
ggb.command('s = Ray(F_2, P_2)') -> 's'
ggb.command("P'_2 = Intersect(s, r)") -> "P'_2"
ggb.command('l1 = {Intersect(g, r)}') -> 'l1'
ggb.command("P'''_2 = l1(1)") -> "P'''_2"
ggb.command("P''_2 = l1(2)") -> "P''_2"
ggb.command("t = Segment(O, P''_2)") -> 't'
ggb.command("b = Line(F_1, P'_2)") -> 'b'
ggb.command("γ = Angle(F_2, P'_2, P''_2)") -> 'γ'
ggb.command("a = Segment(O, P'''_2)") -> 'a'
ggb.command("δ = Angle(F_1, P'_2, P'''_2)") -> 'δ'
ggb.command('f_1 = Line(O, r)') -> 'f_1'
ggb.command('O_{4} = Intersect(f_1, b)') -> 'O_{4}'
ggb.command("g_1 = Segment(O_{4}, P'_2)") -> 'g_1'
ggb.command("m_1 = PerpendicularLine(P'_2, f_1)") -> 'm_1'
ggb.command('T = Intersect(m_1, f_1)') -> 'T'
ggb.command("g_2 = Segment(F_2, P'_2)") -> 'g_2'
ggb.command("h_2 = Segment(P'_2, F_1)") -> 'h_2'
ggb.command("η = Angle(P'_2, T, O_{4})") -> 'η'
ggb.command("q2 = Polygon(O, O_{4}, P'_2, P''_2)") -> 'q2,undefined,undefined,undefined,undefined'
ggb.command('m_2 = Segment(O, O_{4}, q2)') -> None
ggb.command("n_2 = Segment(O_{4}, P'_2, q2)") -> None
ggb.command("p_2 = Segment(P'_2, P''_2, q2)") -> None
ggb.command("q_2 = Segment(P''_2, O, q2)") -> None
ggb.command("cv_{2} = CurvatureVector(P'_2, e)") -> 'cv_{2}'
ggb.command("O_2 = Translate(P'_2, Vector(cv_{2} / Length(cv_{2})²))") -> 'O_2'
ggb.command("s_2 = Circle(O_2, P'_2)") -> 's_2'
ggb.command("f_3 = Segment(P'''_2, F_1)") -> 'f_3'
ggb.command("g_3 = Segment(P'''_2, P_2)") -> 'g_3'
ggb.command("κ = Angle(P''_2, P'''_2, P_2)") -> 'κ'

['F_1',
 'V',
 'F_2',
 'e',
 'O',
 'g',
 'h',
 'l0',
 'I',
 'p',
 'P_2',
 'r',
 's',
 "P'_2",
 'l1',
 "P'''_2",
 "P''_2",
 't',
 'b',
 'γ',
 'a',
 'δ',
 'f_1',
 'O_{4}',
 'g_1',
 'm_1',
 'T',
 'g_2',
 'h_2',
 'η',
 'q2',
 'undefined',
 'undefined',
 'undefined',
 'undefined',
 'cv_{2}',
 'O_2',
 's_2',
 'f_3',
 'g_3',
 'κ']

In [95]:
await ggb.command("O_{4} = Intersect(f_1, b)")

'O_4'

In [104]:
r = await ggb.function('getXML', [['cv_{2}'], ['O_{11}']])

In [107]:
print(r[0])
print(r[1])

<element type="vector" label="cv_2">
	<show object="true" label="false"/>
	<objColor r="110" g="109" b="115" alpha="0"/>
	<layer val="0"/>
	<labelMode val="0"/>
	<lineStyle thickness="5" type="0" typeHidden="1" opacity="204"/>
	<coordStyle style="cartesian"/>
	<startPoint exp="P&apos;_2"/>
	<coords x="0.07911521490160818" y="-0.20178843536465274" z="0"/>
</element>

<expression label="O_{11}" exp="3"/>
<element type="numeric" label="O_{11}">
	<value val="3"/>
	<show object="false" label="true"/>
	<layer val="8"/>
	<labelMode val="1"/>
	<animation type="0" playing="false"/>
</element>

In [169]:
o = c.ggb_schema.decode(c.geogebra_xml)

In [170]:
r = await ggb.function("getAllObjectNames")
_l = [e['@label'] for e in o['element']]
for _n in r:# set(r) - {'xOyPlane', 'l7', 'l8', 'l9', 'l3', 'l2', 'l1', 'l0', 'l6', 'l4', 'l5'}:
    # print(_n)
    if _n in _l:
        _i = _l.index(_n)
        _e = o['element'][_i]
        for _k in ['animation', 'pointSize', 'pointStyle', 'coords', 'eigenvectors', 'eqnStyle', 'matrix', 'show']:
            _e.pop(_k, None)
        _x = xmlschema.etree_tostring(c.ggb_schema.encode(_e, 'element'))
        # print(_x)
        await ggb.function("evalXML", [_x])
    else:
        print(f"{_n}")

I_{3}
I_{1}
l0
l1_{1}
l1_{2}
l1
O_{4}
o
o_{4}
p'_2
p''_2
cv_{2}

In [172]:
_l

["F'_2",
 'F_1',
 'V',
 'c',
 'F_2',
 'e',
 'P_3',
 'i',
 "O'",
 'j',
 'k',
 'm',
 'n',
 'M',
 'O',
 'g',
 'h',
 'D',
 'I',
 'f',
 'd',
 'p',
 'l',
 'β',
 'q',
 'P_2',
 'r',
 's',
 "P'_2",
 "P'''_2",
 "P''_2",
 't',
 'b',
 'γ',
 'a',
 'δ',
 'f_1',
 'O_4',
 'g_1',
 'P_1',
 'h_1',
 'i_1',
 'j_1',
 'k_1',
 'Q',
 'R',
 'q1',
 'b_1',
 'p_1',
 'r_1',
 'q_1',
 'S',
 't1',
 's_1',
 'b_2',
 'c_1',
 'm_1',
 'T',
 'n_1',
 'U',
 'ε',
 'd_1',
 'A',
 'B',
 't_1',
 'a_1',
 'e_1',
 'c_2',
 'C',
 'E',
 'ζ',
 'f_2',
 'g_2',
 'h_2',
 'η',
 'd_2',
 'F',
 'G',
 'α',
 'H',
 'J',
 'l_1',
 'i_2',
 'j_2',
 'θ',
 'e_2',
 'k_2',
 'l_2',
 'K',
 't2',
 'k_3',
 "f'_2",
 'p_3',
 'q2',
 'm_2',
 'n_2',
 'p_2',
 'q_2',
 'ι',
 'cv_1',
 'O_1',
 'r_2',
 'cv_2',
 'O_2',
 's_2',
 'cv_3',
 'O_3',
 't_2',
 'a_2',
 'cv',
 'L',
 'f_3',
 'g_3',
 'κ']

In [141]:
await ggb.function('setLayerVisible', list(zip_longest(range(10), [], fillvalue=False)))
await ggb.function('setLayerVisible', list(zip_longest([9, 0, 3], [], fillvalue=True)))

[None, None, None]