# example of worksheet

In [1]:
%load_ext autoreload
%autoreload 2

In [57]:
import xml.etree.ElementTree as ET
import xmlschema
import polars as pl
import networkx as nx
from itertools import zip_longest

In [3]:
import ggblab

In [4]:
%ggblab api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

## composition of primitives
### cylinder

In [5]:
ls = {i: set() for i in range(10)}
ls

{0: set(),
 1: set(),
 2: set(),
 3: set(),
 4: set(),
 5: set(),
 6: set(),
 7: set(),
 8: set(),
 9: set()}

In [8]:
%ggb api newConstruction()

In [9]:
%%ggblab
C_{t} = Point(zAxis)
C_{b} = Point(zAxis)
SetCoords(C_{t}, 0, 0, 3)
SetCoords(C_{b}, 0, 0, -3)
Cylinder(_1, _2, 1)

['C_{t}', 'C_{b}', 'a', 'c', 'd', 'b']

In [10]:
ls[9] |= set(_)

### control points `Q` and `P`

In [11]:
%%ggblab
O = Intersect(yAxis, xAxis)
e = Circle(yAxis, C_{t})
Q = Point(_)
p = Plane(_, yAxis)
f = IntersectPath(_, a)
P = Point(_)

['O', 'e', 'Q', 'p', 'f', 'P']

In [12]:
ls[9] |= set(_)
ls

{0: set(),
 1: set(),
 2: set(),
 3: set(),
 4: set(),
 5: set(),
 6: set(),
 7: set(),
 8: set(),
 9: {'C_{b}', 'C_{t}', 'O', 'P', 'Q', 'a', 'b', 'c', 'd', 'e', 'f', 'p'}}

In [13]:
i = 9
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [ ]:
%%ggblab
# axis_{z} = Line(C_{t}, C_{b})
# axis_y = Line(O, yAxis)
# axis_x = Line(O, xAxis)

### horizontal

In [88]:
%%ggblab
# p_{xy} = Plane(xAxis, yAxis)

ggb.command failed for: 'k = IntersectPath(xOyPlane, a)' -> GeoGebraAppletError: GeoGebra applet error: Redefinition failed [AppletError]

["{'error': 'GeoGebra applet error: Redefinition failed [AppletError]'}"]

In [133]:
ls[0] |= set(_)

In [89]:
%%ggblab
k_2 = IntersectPath(xOyPlane, a)
l_1 = Line(P, zAxis)
P_{c} = Intersect(_1, _2)
h_2 = PerpendicularLine(P_{c}, yAxis)
h_1 = PerpendicularLine(P, yAxis, space)
P_{h} = Intersect(h_1, h_2)
h_3 = PerpendicularLine(P_{c}, xAxis)
P_{w} = Intersect(h_3, xAxis)
# #
# i_2 = Segment(O, P_{c})
# s_{cw} = Segment(P_{c}, P_{w})
# s_{ch} = Segment(P_{c}, P_{h})

['k_2', 'l_1', 'P_{c}', 'undefined', 'h_2', 'h_1', 'P_{h}', 'h_3', 'P_{w}']

In [90]:
ls[6] |= set(_)

In [91]:
i = 6
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [26]:
%%ggb
l2 = {Intersect(xAxis, b)}
C' = l2(1)
A' = l2(2)

['l2', "C'", "A'"]

### ellipse

In [14]:
%%ggb
xzPlane = Plane(xAxis, zAxis)
l1 = {Intersect(_1, f)}
A = l1(1)
C = l1(2)
l3 = {Intersect(yAxis, f)}
B = l3(1)
D = l3(2)
a_1 = Line(O, Q)
c_1 = Circle(yAxis, A)

['xzPlane', 'l1', 'A', 'C', 'l3', 'B', 'D', 'a_1', 'c_1']

In [473]:
l = ['q', 'l1', 'A', 'C', 'l2', "C'", "A'", 'l3', 'B', 'D', 'a_1']
await ggb.function("setLayer", list(zip(l, [3]*len(l))))

[None, None, None, None, None, None, None, None, None, None, None]

In [15]:
%%ggb
# Line(A, zAxis)
# Line(C, zAxis)
# {AngleBisector(a_1, _1)}
# Element(_3, 1)
# Element(_3, 2)
# {AngleBisector(a_1, _2)}
# Element(_6, 1)
# Element(_6, 2)
l_{10} = Line(A, zAxis)
l_{11} = Line(C, zAxis)
l10 = {AngleBisector(a_1, _1)}
l_{12} = Element(_3, 1)
l_{13} = Element(_3, 2)
l11 = {AngleBisector(a_1, _2)}
l_{14} = Element(_6, 1)
l_{15} = Element(_6, 2)

['l_{10}', 'l_{11}', 'l10', 'l_{12}', 'l_{13}', 'l11', 'l_{14}', 'l_{15}']

In [23]:
%%ggblab
# l4 = {Intersect(zAxis, c_1)}
# O'' = l4(1)
# O''' = l4(2)
O'' = Intersect(l_{13}, l_{14})
O''' = Intersect(l_{12}, l_{15})

["O''", "O'''"]

In [24]:
%%ggb 
f_2 = PerpendicularLine(O'', p)
f_1 = PerpendicularLine(O''', p)
F_2 = Intersect(f_2, p)
F_1 = Intersect(f_1, p)

['f_2', 'f_1', 'F_2', 'F_1']

In [27]:
%%ggb
g = Segment(O, A)
i = Segment(O, A')
j = Segment(B, O)
# s = Segment(P, P_{c})
h = Segment(A', A)
# r = Segment(P, P_{h})
# g_2 = Segment(O, P)
i_1 = Segment(O'', O)
j_1 = Segment(O'', F_2)
k_1 = Segment(F_2, O)

['g', 'i', 'j', 'h', 'i_1', 'j_1', 'k_1']

In [29]:
%%ggb
Line(O, f_1)
Circle(_, B)
Circle(_1, A)
Circle(_1, F_1)

['k', 'q', 'r', 's']

### post analysis

In [30]:
%%ggb
g_1 = Segment(B, F_1)
r_1 = Segment(O, F_1)
b_1 = Segment(B, F_2)

['g_1', 'r_1', 'b_1']

In [38]:
%%ggb
o = Sphere(O'', F_2)
u_{1} = Sphere(O''', F_1)
p_1 = Plane(O'', xOyPlane)
q_1 = Plane(O''', xOyPlane)
d_1 = IntersectPath(p_1, a)
e_1 = IntersectPath(q_1, a)
l7 = {Intersect(l_1, d_1)}
l8 = {Intersect(l_1, e_1)}
P'' = l7(1)
P''' = l8(1)
l = Segment(P'', P)
m = Segment(P, P''')

['o', 'u_{1}', 'p_1', 'q_1', 'd_1', 'e_1', 'l7', 'l8', "P''", "P'''", 'l', 'm']

In [92]:
%%ggb
n_2 = Segment(P, F_2)
n_1 = Segment(P, F_1)
u = Vector(P_{h}, P)
v = Vector(P_{h}, P_{c})
n = Translate(Vector((((u * v)) / ((v * v)) * v)), P_{h})
t = Line(O, P_{w})
t_1 = Segment(O, P_{h})
j_2 = Segment(P_{h}, P_{c})
l9 = {Intersect(yAxis, k_2)}
E = l9(1)
F = l9(2)
s_1 = Segment(E, F)

['n_2', 'n_1', 'u', 'v', 'n', 't', 't_1', 'j_2', 'l9', 'E', 'F', 's_1']

In [93]:
ls[6] |= set(_)

In [94]:
i = 6
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [45]:
%%ggb
t1 = Polygon(O, P_{c}, P_{h})
# p_{h} = Segment(O, P_{c}, t1)
# o_1 = Segment(P_{c}, P_{h}, t1)
# p_{c} = Segment(P_{h}, O, t1)
t2 = Polygon(O, P, P_{h})
# k_2 = Segment(O, P, t2)
# o_2 = Segment(P, P_{h}, t2)
# p_2 = Segment(P_{h}, O, t2)

['t1', 'p_{h}', 'o_1', 'p_{c}', 't2', 't', 'o_2', 'p_2']

In [168]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [169]:
df.write_parquet('2025_02_03.parquet')

In [106]:
lc = {}
for i in range(10):
    _df = df.filter(pl.col("Layer") == i)
    ls[i] = set(_df["Name"].to_list())
    lc[i] = ConstructionIO.commands_for_magic(_df, use_name_equals=True)

In [101]:
for i in range(10):
    l = list(zip_longest(ls[i], [], fillvalue=i))
    # print(l)
    await ggb.function('setLayer', l)

In [102]:
for i in range(10):
    await ggb.function('setLayerVisible', [i, False])

In [104]:
await ggb.function('setLayerVisible', [0, True])

In [110]:
print(lc[9])

e = Circle(yAxis, C_{t})
Q = Point(e)
P = Point(f)

In [111]:
print(lc[8])

l1 = {Intersect(xzPlane, f)}
l3 = {Intersect(yAxis, f)}
l10 = {AngleBisector(a_1, l_{10})}
l11 = {AngleBisector(a_1, l_{11})}
l2 = {Intersect(xAxis, b)}
l7 = {Intersect(l_1, d_1)}
l8 = {Intersect(l_1, e_1)}

In [108]:
print(lc[0])

C_{t} = Point(zAxis)
C_{b} = Point(zAxis)
a = Cylinder(C_{t}, C_{b}, 1)
b = Cylinder(C_{t}, C_{b}, 1)
c = Cylinder(C_{t}, C_{b}, 1)
d = Cylinder(C_{t}, C_{b}, 1)

In [109]:
print(lc[1])

xzPlane = Plane(xAxis, zAxis)
c_1 = Circle(yAxis, A)
l_{10} = Line(A, zAxis)
l_{11} = Line(C, zAxis)
l_{12} = Element(l10, 1)
l_{13} = Element(l10, 2)
l_{14} = Element(l11, 1)
l_{15} = Element(l11, 2)
f_2 = PerpendicularLine(O'', p)
f_1 = PerpendicularLine(O''', p)
k = Line(O, f_1)

In [112]:
print(lc[2])

O = Intersect(yAxis, xAxis)
A = l1(1)
C = l1(2)
a_1 = Line(O, Q)
O'' = Intersect(l_{13}, l_{14})
O''' = Intersect(l_{12}, l_{15})
F_2 = Intersect(f_2, p)
F_1 = Intersect(f_1, p)
C' = l2(1)
A' = l2(2)

In [113]:
print(lc[3])

g = Segment(O, A)
i = Segment(O, A')
h = Segment(A', A)
i_1 = Segment(O'', O)
j_1 = Segment(O'', F_2)
k_1 = Segment(F_2, O)

In [114]:
print(lc[4])

p = Plane(Q, yAxis)
f = IntersectPath(p, a)
B = l3(1)
D = l3(2)

In [115]:
print(lc[5])

j = Segment(B, O)
q = Circle(k, B)
r = Circle(k, A)
s = Circle(k, F_1)
g_1 = Segment(B, F_1)
r_1 = Segment(O, F_1)
b_1 = Segment(B, F_2)

In [116]:
print(lc[7])

o = Sphere(O'', F_2)
u_{1} = Sphere(O''', F_1)
p_1 = Plane(O'', xOyPlane)
q_1 = Plane(O''', xOyPlane)
d_1 = IntersectPath(p_1, a)
e_1 = IntersectPath(q_1, a)
P'' = l7(1)
P''' = l8(1)
l = Segment(P'', P)
m = Segment(P, P''')

In [117]:
print(lc[7])

o = Sphere(O'', F_2)
u_{1} = Sphere(O''', F_1)
p_1 = Plane(O'', xOyPlane)
q_1 = Plane(O''', xOyPlane)
d_1 = IntersectPath(p_1, a)
e_1 = IntersectPath(q_1, a)
P'' = l7(1)
P''' = l8(1)
l = Segment(P'', P)
m = Segment(P, P''')

In [118]:
df["Type"].unique()

shape: (11,)
Series: 'Type' [str]
[
	"surface"
	"cylinder"
	"segment"
	"point"
	"list"
	"line"
	"vector"
	"sphere"
	"circle"
	"plane"
	"ellipse"
]

In [119]:
df.filter(pl.col("Type") == "plane")

shape: (4, 10)
┌──────────┬─────────┬───────┬─────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name    ┆ Type  ┆ Command         ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---     ┆ ---   ┆ ---             ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str     ┆ str   ┆ str             ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪═════════╪═══════╪═════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 10       ┆ p       ┆ plane ┆ Plane(Q, yAxis) ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│ 13       ┆ xzPlane ┆ plane ┆ Plane(xAxis,    ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆         ┆       ┆ zAxis)          ┆   ┆       ┆            ┆           ┆           │
│ 55       ┆ p_1     ┆ plane ┆ Plane(O'',      ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆         ┆       ┆ xOyPlane)       ┆   ┆       ┆            ┆           ┆           │
│ 56       ┆ q_1     ┆ plane ┆ Plane(O''',     ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆         ┆       ┆ xOyPlane)       ┆   ┆       ┆            ┆           ┆           │
└──────────┴─────────┴───────┴─────────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [164]:
df.filter(pl.col("Type") == "circle")

shape: (10, 10)
┌──────────┬──────┬────────┬──────────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name ┆ Type   ┆ Command              ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---  ┆ ---    ┆ ---                  ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str  ┆ str    ┆ str                  ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪══════╪════════╪══════════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 5        ┆ c    ┆ circle ┆ Cylinder(C_{t},      ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆      ┆        ┆ C_{b}, 1)            ┆   ┆       ┆            ┆           ┆           │
│ 6        ┆ d    ┆ circle ┆ Cylinder(C_{t},      ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆      ┆        ┆ C_{b}, 1)            ┆   ┆       ┆            ┆           ┆           │
│ 8        ┆ e    ┆ circle ┆ Circle(yAxis, C_{t}) ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│ 21       ┆ c_1  ┆ circle ┆ Circle(yAxis, A)     ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│ 47       ┆ q    ┆ circle ┆ Circle(k, B)         ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 48       ┆ r    ┆ circle ┆ Circle(k, A)         ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 49       ┆ s    ┆ circle ┆ Circle(k, F_1)       ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 57       ┆ d_1  ┆ circle ┆ IntersectPath(p_1,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆      ┆        ┆ a)                   ┆   ┆       ┆            ┆           ┆           │
│ 58       ┆ e_1  ┆ circle ┆ IntersectPath(q_1,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆      ┆        ┆ a)                   ┆   ┆       ┆            ┆           ┆           │
│ 69       ┆ k_2  ┆ circle ┆ IntersectPath(xOyPla ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆        ┆ ne, a)               ┆   ┆       ┆            ┆           ┆           │
└──────────┴──────┴────────┴──────────────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [148]:
df.filter(pl.col("Type") == "line")["Value"].to_list()

['a_1: X = (0, 0, 0) + λ (2.63, 0, -1.44)',
 'l_{10}: X = (1, 0, -0.54) + λ (0, 0, 1)',
 'l_{11}: X = (-1, 0, 0.54) + λ (0, 0, 1)',
 'l_{12}: X = (1, 0, -0.54) + λ (0.88, 0, 0.52)',
 'l_{13}: X = (1, 0, -0.54) + λ (0.88, 0, -1.48)',
 'l_{14}: X = (-1, 0, 0.54) + λ (0.88, 0, 0.52)',
 'l_{15}: X = (-1, 0, 0.54) + λ (0.88, 0, -1.48)',
 'f_2: X = (0, 0, 1.14) + λ (-1.44, 0, -2.63)',
 'f_1: X = (0, 0, -1.14) + λ (-1.44, 0, -2.63)',
 'k: X = (0, 0, 0) + λ (-0.48, 0, -0.88)',
 'l_1: X = (0.61, 0.79, -0.33) + λ (0, 0, 1)',
 'h_1: X = (0.61, 0.79, -0.33) + λ (0.88, 0, -0.48)',
 'h_2: X = (0.61, 0.79, 0) + λ (1, 0, 0)',
 'h_3: X = (0.61, 0.79, 0) + λ (0, 1, 0)',
 't: X = (0, 0, 0) + λ (0.61, 0, 0)']

In [133]:
from sympy import Line3D, Segment, Point3D, Eq, Plane
from sympy.abc import x, y, a, b

In [129]:
l = Line3D(Point3D(0,0,0), direction_ratio=(0,0,1))

In [132]:
l.equation()

(x, y)

In [137]:
xzPlane = Plane(Point3D(0,0,0), Point3D(1,0,0), Point3D(0,0,1))

In [139]:
xzPlane.normal_vector

(0, -1, 0)

In [150]:
for p in df.filter(pl.col("Type") == "point")["Value"]:
    t = ggb.parser.tokenize(p)
    # print(t)
    print(xzPlane.distance(Point3D(t[2])))

0
0
0
0
79/100
0
0
1
1
0
0
0
0
0
0
79/100
79/100
79/100
79/100
0
1
1

In [167]:
for p in df.filter(pl.col("Type") == "circle")["Value"]:
    t = ggb.parser.tokenize(p)
    print(p)
    # print(xzPlane.distance(Point3D(t[2])))

c: X = (0, 0, 3) + (cos(t), sin(t), 0)
d: X = (0, 0, -3) + (cos(t), - sin(t), 0)
e: X = (0, 0, 0) + (3 sin(t), 0, 3 cos(t))
c_1: X = (0, 0, 0) + (cos(t) - 0.54 sin(t), 0, -0.54 cos(t) -  sin(t))
q: X = (0, 0, 0) + (0.88 sin(t), cos(t), -0.48 sin(t))
r: X = (0, 0, 0) + (cos(t), -1.14 sin(t), -0.54 cos(t))
s: X = (0, 0, 0) + (0.48 cos(t), -0.54 sin(t), -0.26 cos(t))
d_1: X = (0, 0, 1.14) + (cos(t), sin(t), 0)
e_1: X = (0, 0, -1.14) + (cos(t), sin(t), 0)
k_2: X = (0, 0, 0) + (cos(t), sin(t), 0)

In [201]:
s0 = set()
s1 = set(df.filter(pl.col("Layer").is_in([0, 1, 2, 3, 4, 5, 6, 7]) & ~pl.col("Type").is_in(["numeric"]))["Name"])
s2 = set(['xAxis', 'yAxis', 'zAxis']) | nx.ancestors(g1, "P") | {"P"} | {"c", "d", "b"}

for _n in s1:
    # print(f"{_n} {nx.ancestors(g1, _n)}")
    s0 |= nx.ancestors(g1, _n) | {_n}

s0 - s1 - s2

{'xOyPlane'}

In [202]:
r = await ggb.function("getAllObjectNames")

In [203]:
s3 = (s0 | nx.ancestors(g1, "l_1") | nx.ancestors(g1, "h_1")) - s2
s3 -= set(r)
s3

{"P''", "P'''", 'd_1', 'e_1', 'l', 'm', 'o', 'p_1', 'q_1', 'u_{1}', 'xOyPlane'}

In [204]:
df.filter(pl.col("Name").is_in(s3) & ~pl.col("Type").is_in(["numeric"]))

shape: (10, 10)
┌──────────┬───────┬─────────────┬────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name  ┆ Type        ┆ Command        ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---   ┆ ---         ┆ ---            ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str   ┆ str         ┆ str            ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪═══════╪═════════════╪════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 35       ┆ o     ┆ quadric     ┆ Sphere(O'',    ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆             ┆ F_2)           ┆   ┆       ┆            ┆           ┆           │
│ 36       ┆ u_{1} ┆ quadric     ┆ Sphere(O''',   ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆             ┆ F_1)           ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ p_1   ┆ plane3d     ┆ Plane(O'',     ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆             ┆ xOyPlane)      ┆   ┆       ┆            ┆           ┆           │
│ 38       ┆ q_1   ┆ plane3d     ┆ Plane(O''',    ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆             ┆ xOyPlane)      ┆   ┆       ┆            ┆           ┆           │
│ 39       ┆ d_1   ┆ conic3dpart ┆ IntersectPath( ┆ … ┆ 7     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆             ┆ p_1, a)        ┆   ┆       ┆            ┆           ┆           │
│ 40       ┆ e_1   ┆ conic3dpart ┆ IntersectPath( ┆ … ┆ 7     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆             ┆ q_1, a)        ┆   ┆       ┆            ┆           ┆           │
│ 46       ┆ P''   ┆ point3d     ┆ Intersect(l_1, ┆ … ┆ 7     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆             ┆ d_1)           ┆   ┆       ┆            ┆           ┆           │
│ 47       ┆ P'''  ┆ point3d     ┆ Intersect(l_1, ┆ … ┆ 7     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆             ┆ e_1)           ┆   ┆       ┆            ┆           ┆           │
│ 48       ┆ l     ┆ segment3d   ┆ Segment(P'',   ┆ … ┆ 7     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆             ┆ P)             ┆   ┆       ┆            ┆           ┆           │
│ 49       ┆ m     ┆ segment3d   ┆ Segment(P,     ┆ … ┆ 7     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆             ┆ P''')          ┆   ┆       ┆            ┆           ┆           │
└──────────┴───────┴─────────────┴────────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [221]:
s3 = set(df.filter(pl.col("Layer").is_in([9, 8]))["Name"]) - {'P'}
s3
# cmds = ConstructionIO.commands_for_magic(df.filter(pl.col("Layer").is_in([9, 8])), use_name_equals=True)
# print(cmds)

{'E',
 'F',
 'j_2',
 'k_2',
 'n',
 'n_1',
 'n_2',
 'o_1',
 'o_2',
 'p_2',
 'p_{c}',
 'p_{h}',
 's_1',
 't',
 't1',
 't2',
 't_1',
 'u',
 'v'}

In [205]:
cmds = ConstructionIO.commands_for_magic(df.filter(df["Name"].is_in(s3)), use_name_equals=True)
print(cmds)

o = Sphere(O'', F_2)
u_{1} = Sphere(O''', F_1)
p_1 = Plane(O'', xOyPlane)
q_1 = Plane(O''', xOyPlane)
d_1 = IntersectPath(p_1, a)
e_1 = IntersectPath(q_1, a)
P'' = Intersect(l_1, d_1)
P''' = Intersect(l_1, e_1)
l = Segment(P'', P)
m = Segment(P, P''')

### finding ancestors

In [111]:
nx.ancestors(g1, "Q")

{'C_{t}', 'e', 'yAxis', 'zAxis'}

In [112]:
nx.ancestors(g1, "P")

{'C_{b}', 'C_{t}', 'Q', 'a', 'e', 'f', 'p', 'yAxis', 'zAxis'}

In [118]:
cmds = ConstructionIO.commands_for_magic(df.filter(df["Name"].is_in(nx.ancestors(g1, 'P') | {'P'})), use_name_equals=True)
print(cmds)

C_{t} = Point(zAxis)
C_{b} = Point(zAxis)
a = Cylinder(C_{t}, C_{b}, 1)
e = Circle(yAxis, C_{t})
Q = Point(e)
p = Plane(Q, yAxis)
f = IntersectPath(p, a)
P = Point(f)

In [48]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [49]:
df = await ConstructionIO.initialize_dataframe(ggb, file='2025_02_03.ggb')

In [53]:
p = ConstructionTreeParser(df)

In [54]:
g1 = p.parse()

In [64]:
cmds = ConstructionIO.commands_for_magic(p.df.filter(~pl.col("Type").is_in(["numeric"])), use_name_equals=True)
print(cmds)

C_{t} = Point(zAxis)
C_{b} = Point(zAxis)
a = Cylinder(C_{t}, C_{b}, 1)
c = Cylinder(C_{t}, C_{b}, 1)
d = Cylinder(C_{t}, C_{b}, 1)
b = Cylinder(C_{t}, C_{b}, 1)
e = Circle(yAxis, C_{t})
Q = Point(e)
p = Plane(Q, yAxis)
f = IntersectPath(p, a)
q = Plane(xAxis, zAxis)
A = Intersect(q, f)
C = Intersect(q, f)
C' = Intersect(xAxis, b)
A' = Intersect(xAxis, b)
O = Intersect(yAxis, xAxis)
g = Segment(O, A)
i = Segment(O, A')
p_{xy} = Plane(xAxis, yAxis)
k = IntersectPath(p_{xy}, a)
B = Intersect(yAxis, f)
D = Intersect(yAxis, f)
j = Segment(B, O)
c_1 = Circle(yAxis, C)
O'' = Intersect(zAxis, c_1)
O''' = Intersect(zAxis, c_1)
f_2 = PerpendicularLine(O'', p)
f_1 = PerpendicularLine(O''', p)
F_2 = Intersect(f_2, p)
F_1 = Intersect(f_1, p)
g_1 = Segment(B, F_1)
i_1 = Segment(O'', O)
j_1 = Segment(O'', F_2)
k_1 = Segment(F_2, O)
o = Sphere(O'', F_2)
u_{1} = Sphere(O''', F_1)
p_1 = Plane(O'', xOyPlane)
q_1 = Plane(O''', xOyPlane)
d_1 = IntersectPath(p_1, a)
e_1 = IntersectPath(q_1, a)
P = Point(f)
l_1 = Line(P, zAxis)
n_2 = Segment(P, F_2)
n_1 = Segment(P, F_1)
r_1 = Segment(O, F_1)
P'' = Intersect(l_1, d_1)
P''' = Intersect(l_1, e_1)
l = Segment(P'', P)
m = Segment(P, P''')
P_{c} = Intersect(l_1, k)
s = Segment(P, P_{c})
h = Segment(A', A)
h_2 = PerpendicularLine(P_{c}, yAxis, space)
h_1 = PerpendicularLine(P, yAxis, space)
P_{h} = Intersect(h_1, h_2)
axis_{z} = Line(C_{t}, C_{b})
axis_y = Line(O, yAxis)
a_1 = Line(O, Q)
b_1 = Segment(B, F_2)
u = Vector(P_{h}, P)
v = Vector(P_{h}, P_{c})
n = Translate(Vector((((u * v)) / ((v * v)) * v)), P_{h})
h_3 = PerpendicularLine(P_{c}, xAxis, space)
P_{w} = Intersect(h_3, xAxis)
axis_x = Line(O, xAxis)
s_{cw} = Segment(P_{c}, P_{w})
s_{ch} = Segment(P_{c}, P_{h})
i_2 = Segment(O, P_{c})
r = Segment(P, P_{h})
t1 = Polygon(O, P_{c}, P_{h})
p_{h} = Segment(O, P_{c}, t1)
o_1 = Segment(P_{c}, P_{h}, t1)
p_{c} = Segment(P_{h}, O, t1)
t = Line(O, P_{w})
t_1 = Segment(O, P_{h})
j_2 = Segment(P_{h}, P_{c})
E = Intersect(axis_y, k)
F = Intersect(axis_y, k)
s_1 = Segment(E, F)
g_2 = Segment(O, P)
t2 = Polygon(O, P, P_{h})
k_2 = Segment(O, P, t2)
o_2 = Segment(P, P_{h}, t2)
p_2 = Segment(P_{h}, O, t2)

In [63]:
p.df

shape: (87, 11)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Sequence ┆ Name     ┆ Type       ┆ Command   ┆ … ┆ ShowObjec ┆ ShowLabel ┆ Auxiliary ┆ DependsOn │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ t         ┆ ---       ┆ ---       ┆ ---       │
│ u32      ┆ str      ┆ str        ┆ str       ┆   ┆ ---       ┆ bool      ┆ bool      ┆ list[str] │
│          ┆          ┆            ┆           ┆   ┆ bool      ┆           ┆           ┆           │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ C_{t}    ┆ point3d    ┆ Point(zAx ┆ … ┆ false     ┆ true      ┆ true      ┆ ["zAxis"] │
│          ┆          ┆            ┆ is)       ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ C_{b}    ┆ point3d    ┆ Point(zAx ┆ … ┆ false     ┆ true      ┆ true      ┆ ["zAxis"] │
│          ┆          ┆            ┆ is)       ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ a        ┆ quadriclim ┆ Cylinder( ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆ ited       ┆ C_{t},    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ C_{b}, 1) ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 4        ┆ c        ┆ conic3d    ┆ Cylinder( ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ C_{t},    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ C_{b}, 1) ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 5        ┆ d        ┆ conic3d    ┆ Cylinder( ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ C_{t},    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ C_{b}, 1) ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 6        ┆ b        ┆ quadricpar ┆ Cylinder( ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆ t          ┆ C_{t},    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ C_{b}, 1) ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 7        ┆ e        ┆ conic3d    ┆ Circle(yA ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{t}", │
│          ┆          ┆            ┆ xis,      ┆   ┆           ┆           ┆           ┆ "yAxis",  │
│          ┆          ┆            ┆ C_{t})    ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 8        ┆ Q        ┆ point3d    ┆ Point(e)  ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{t}", │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "e", …    │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 9        ┆ p        ┆ plane3d    ┆ Plane(Q,  ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{t}", │
│          ┆          ┆            ┆ yAxis)    ┆   ┆           ┆           ┆           ┆ "Q", …    │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 10       ┆ f        ┆ conic3dpar ┆ Intersect ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆ t          ┆ Path(p,   ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ a)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 11       ┆ q        ┆ plane3d    ┆ Plane(xAx ┆ … ┆ false     ┆ false     ┆ false     ┆ ["xAxis", │
│          ┆          ┆            ┆ is,       ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│          ┆          ┆            ┆ zAxis)    ┆   ┆           ┆           ┆           ┆           │
│ 12       ┆ A        ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (q, f)    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 13       ┆ C        ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (q, f)    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 14       ┆ C'       ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (xAxis,   ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ b)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 15       ┆ A'       ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (xAxis,   ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ b)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 16       ┆ O        ┆ point      ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["xAxis", │
│          ┆          ┆            ┆ (yAxis,   ┆   ┆           ┆           ┆           ┆ "yAxis"]  │
│          ┆          ┆            ┆ xAxis)    ┆   ┆           ┆           ┆           ┆           │
│ 17       ┆ g        ┆ segment3d  ┆ Segment(O ┆ … ┆ true      ┆ false     ┆ false     ┆ ["A",     │
│          ┆          ┆            ┆ , A)      ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 18       ┆ i        ┆ segment3d  ┆ Segment(O ┆ … ┆ true      ┆ false     ┆ false     ┆ ["A'",    │
│          ┆          ┆            ┆ , A')     ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 19       ┆ p_{xy}   ┆ plane3d    ┆ Plane(xAx ┆ … ┆ false     ┆ false     ┆ false     ┆ ["xAxis", │
│          ┆          ┆            ┆ is,       ┆   ┆           ┆           ┆           ┆ "yAxis"]  │
│          ┆          ┆            ┆ yAxis)    ┆   ┆           ┆           ┆           ┆           │
│ 20       ┆ k        ┆ conic3dpar ┆ Intersect ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆ t          ┆ Path(p_{x ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ y}, a)    ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 21       ┆ B        ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (yAxis,   ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ f)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 22       ┆ D        ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (yAxis,   ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆ f)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 23       ┆ j        ┆ segment3d  ┆ Segment(B ┆ … ┆ true      ┆ false     ┆ false     ┆ ["B",     │
│          ┆          ┆            ┆ , O)      ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 24       ┆ c_1      ┆ conic3d    ┆ Circle(yA ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ xis, C)   ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 25       ┆ O''      ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ (zAxis,   ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ c_1)      ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 26       ┆ O'''     ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ (zAxis,   ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ c_1)      ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 27       ┆ f_2      ┆ line3d     ┆ Perpendic ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ ularLine( ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ O'', p)   ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 28       ┆ f_1      ┆ line3d     ┆ Perpendic ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ ularLine( ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ O''', p)  ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 29       ┆ F_2      ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ (f_2, p)  ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 30       ┆ F_1      ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ (f_1, p)  ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 31       ┆ g_1      ┆ segment3d  ┆ Segment(B ┆ … ┆ false     ┆ false     ┆ false     ┆ ["B",     │
│          ┆          ┆            ┆ , F_1)    ┆   ┆           ┆           ┆           ┆ "C", …    │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 32       ┆ i_1      ┆ segment3d  ┆ Segment(O ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ '', O)    ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 33       ┆ j_1      ┆ segment3d  ┆ Segment(O ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ '', F_2)  ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 34       ┆ k_1      ┆ segment3d  ┆ Segment(F ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ _2, O)    ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 35       ┆ o        ┆ quadric    ┆ Sphere(O' ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ ', F_2)   ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 36       ┆ u_{1}    ┆ quadric    ┆ Sphere(O' ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ '', F_1)  ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 37       ┆ p_1      ┆ plane3d    ┆ Plane(O'' ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C",     │
│          ┆          ┆            ┆ ,         ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ xOyPlane) ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 38       ┆ q_1      ┆ plane3d    ┆ Plane(O'' ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C",     │
│          ┆          ┆            ┆ ',        ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ xOyPlane) ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 39       ┆ d_1      ┆ conic3dpar ┆ Intersect ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆ t          ┆ Path(p_1, ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ a)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 40       ┆ e_1      ┆ conic3dpar ┆ Intersect ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆ t          ┆ Path(q_1, ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ a)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 41       ┆ P        ┆ point3d    ┆ Point(f)  ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 42       ┆ l_1      ┆ line3d     ┆ Line(P,   ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ zAxis)    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 43       ┆ n_2      ┆ segment3d  ┆ Segment(P ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ , F_2)    ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 44       ┆ n_1      ┆ segment3d  ┆ Segment(P ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ , F_1)    ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 45       ┆ r_1      ┆ segment3d  ┆ Segment(O ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ , F_1)    ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 46       ┆ P''      ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ (l_1,     ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ d_1)      ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 47       ┆ P'''     ┆ point3d    ┆ Intersect ┆ … ┆ true      ┆ true      ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ (l_1,     ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆ e_1)      ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 48       ┆ l        ┆ segment3d  ┆ Segment(P ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ '', P)    ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 49       ┆ m        ┆ segment3d  ┆ Segment(P ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C",     │
│          ┆          ┆            ┆ , P''')   ┆   ┆           ┆           ┆           ┆ "C_{b}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 50       ┆ P_{c}    ┆ point3d    ┆ Intersect ┆ … ┆ false     ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ (l_1, k)  ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 51       ┆ s        ┆ segment3d  ┆ Segment(P ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆            ┆ , P_{c})  ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 52       ┆ h        ┆ segment3d  ┆ Segment(A ┆ … ┆ true      ┆ false     ┆ false     ┆ ["A",     │
│          ┆          ┆            ┆ ', A)     ┆   ┆           ┆           ┆           ┆ "A'", …   │

In [75]:
rem = set(p.df["Name"]) - set(await ggb.function('getAllObjectNames'))

In [79]:
p.df.filter(pl.col("Name").is_in(rem) & ~pl.col("Type").is_in(["numeric"]))#["Name", "Command"]

shape: (28, 11)
┌──────────┬──────────┬───────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Sequence ┆ Name     ┆ Type      ┆ Command    ┆ … ┆ ShowObjec ┆ ShowLabel ┆ Auxiliary ┆ DependsOn │
│ ---      ┆ ---      ┆ ---       ┆ ---        ┆   ┆ t         ┆ ---       ┆ ---       ┆ ---       │
│ u32      ┆ str      ┆ str       ┆ str        ┆   ┆ ---       ┆ bool      ┆ bool      ┆ list[str] │
│          ┆          ┆           ┆            ┆   ┆ bool      ┆           ┆           ┆           │
╞══════════╪══════════╪═══════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 19       ┆ p_{xy}   ┆ plane3d   ┆ Plane(xAxi ┆ … ┆ false     ┆ false     ┆ false     ┆ ["xAxis", │
│          ┆          ┆           ┆ s, yAxis)  ┆   ┆           ┆           ┆           ┆ "yAxis"]  │
│ 50       ┆ P_{c}    ┆ point3d   ┆ Intersect( ┆ … ┆ false     ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ l_1, k)    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 53       ┆ h_2      ┆ line3d    ┆ Perpendicu ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ larLine(P_ ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ {c},       ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆ yAxis…     ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 55       ┆ P_{h}    ┆ point3d   ┆ Intersect( ┆ … ┆ false     ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ h_1, h_2)  ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 58       ┆ axis_{z} ┆ line3d    ┆ Line(C_{t} ┆ … ┆ true      ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ , C_{b})   ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 59       ┆ axis_y   ┆ line      ┆ Line(O,    ┆ … ┆ true      ┆ false     ┆ false     ┆ ["O",     │
│          ┆          ┆           ┆ yAxis)     ┆   ┆           ┆           ┆           ┆ "xAxis",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "yAxis"]  │
│ 62       ┆ u        ┆ vector3d  ┆ Vector(P_{ ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ h}, P)     ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 63       ┆ v        ┆ vector3d  ┆ Vector(P_{ ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ h}, P_{c}) ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 64       ┆ n        ┆ vector3d  ┆ Translate( ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ Vector(((( ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ u * v)) /  ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆ …          ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 65       ┆ h_3      ┆ line3d    ┆ Perpendicu ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ larLine(P_ ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ {c},       ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆ xAxis…     ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 66       ┆ P_{w}    ┆ point3d   ┆ Intersect( ┆ … ┆ false     ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ h_3,       ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ xAxis)     ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 67       ┆ axis_x   ┆ line      ┆ Line(O,    ┆ … ┆ false     ┆ false     ┆ false     ┆ ["O",     │
│          ┆          ┆           ┆ xAxis)     ┆   ┆           ┆           ┆           ┆ "xAxis",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "yAxis"]  │
│ 68       ┆ s_{cw}   ┆ segment3d ┆ Segment(P_ ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ {c},       ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ P_{w})     ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 69       ┆ s_{ch}   ┆ segment3d ┆ Segment(P_ ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ {c},       ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ P_{h})     ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 70       ┆ i_2      ┆ segment3d ┆ Segment(O, ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ P_{c})     ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 72       ┆ t1       ┆ polygon3d ┆ Polygon(O, ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ P_{c},     ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ P_{h})     ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 73       ┆ p_{h}    ┆ segment3d ┆ Segment(O, ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ P_{c}, t1) ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 74       ┆ o_1      ┆ segment3d ┆ Segment(P_ ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ {c},       ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ P_{h}, t1) ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 75       ┆ p_{c}    ┆ segment3d ┆ Segment(P_ ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ {h}, O,    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ t1)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 77       ┆ t        ┆ line3d    ┆ Line(O,    ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ P_{w})     ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 78       ┆ t_1      ┆ segment3d ┆ Segment(O, ┆ … ┆ false     ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ P_{h})     ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 79       ┆ j_2      ┆ segment3d ┆ Segment(P_ ┆ … ┆ false     ┆ true      ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ {h},       ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ P_{c})     ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 82       ┆ s_1      ┆ segment3d ┆ Segment(E, ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ F)         ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 83       ┆ g_2      ┆ segment3d ┆ Segment(O, ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ P)         ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 84       ┆ t2       ┆ polygon3d ┆ Polygon(O, ┆ … ┆ false     ┆ false     ┆ false     ┆ ["C_{b}", │
│          ┆          ┆           ┆ P, P_{h})  ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 85       ┆ k_2      ┆ segment3d ┆ Segment(O, ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ P, t2)     ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 86       ┆ o_2      ┆ segment3d ┆ Segment(P, ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ P_{h}, t2) ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
│ 87       ┆ p_2      ┆ segment3d ┆ Segment(P_ ┆ … ┆ false     ┆ false     ┆ true      ┆ ["C_{b}", │
│          ┆          ┆           ┆ {h}, O,    ┆   ┆           ┆           ┆           ┆ "C_{t}",  │
│          ┆          ┆           ┆ t2)        ┆   ┆           ┆           ┆           ┆ …         │
│          ┆          ┆           ┆            ┆   ┆           ┆           ┆           ┆ "zAxis"]  │
└──────────┴──────────┴───────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [81]:
nx.descendants(g1, 'p')

{'A',
 'B',
 'C',
 'D',
 'F_1',
 'F_2',
 "O''",
 "O'''",
 'P',
 "P''",
 "P'''",
 'P_{c}',
 'P_{h}',
 'P_{w}',
 'b_1',
 'c_1',
 'd_1',
 'e_1',
 'f',
 'f_1',
 'f_2',
 'g',
 'g_1',
 'g_2',
 'h',
 'h_1',
 'h_2',
 'h_3',
 'i_1',
 'i_2',
 'j',
 'j_1',
 'j_2',
 'k_1',
 'k_2',
 'l',
 'l_1',
 'm',
 'm_1',
 'n',
 'n_1',
 'n_2',
 'o',
 'o_1',
 'o_2',
 'p_1',
 'p_2',
 'p_{c}',
 'p_{h}',
 'q_1',
 'r',
 'r_1',
 's',
 's_{ch}',
 's_{cw}',
 't',
 't1',
 't2',
 't_1',
 'u',
 'u_{1}',
 'v',
 'v_{1}',
 'w'}

In [83]:
await ggb.function('setLayerVisible', list(zip_longest(range(10), [], fillvalue=False)))

[None, None, None, None, None, None, None, None, None, None]

In [86]:
await ggb.function('setVisible', list(zip_longest(nx.descendants(g1, 'p'), [], fillvalue=True)))

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

## attributs

In [17]:
c = ggb.file.load('2025_02_03.ggb')

In [18]:
o = c.ggb_schema.decode(c.geogebra_xml)

In [98]:
r = await ggb.function("getAllObjectNames")
for _n in r:# set(r) - {'xOyPlane', 'l7', 'l8', 'l9', 'l3', 'l2', 'l1', 'l0', 'l6', 'l4', 'l5'}:
    print(_n)
    try:
        _i = [e['@label'] for e in o['element']].index(_n)
        _e = o['element'][_i]
        for _k in ['animation', 'pointSize', 'pointStyle', 'coords', 'eigenvectors', 'eqnStyle', 'matrix', 'show']:
            _e.pop(_k, None)
        _x = xmlschema.etree_tostring(c.ggb_schema.encode(_e, 'element'))
        print(_x)
        await ggb.function("evalXML", [_x])
    except Exception as e:
        print(e)
        pass

C_{t}
<element type="point3d" label="C_{t}">
    <objColor r="21" g="101" b="192" alpha="0.0" />
    <layer val="0" />
    <labelMode val="0" />
    <auxiliary val="true" />
</element>
C_{b}
<element type="point3d" label="C_{b}">
    <objColor r="21" g="101" b="192" alpha="0.0" />
    <layer val="0" />
    <labelMode val="0" />
    <auxiliary val="true" />
</element>
a
<element type="quadriclimited" label="a">
    <objColor r="216" g="27" b="96" alpha="0.4000000059604645" />
    <layer val="0" />
    <labelMode val="0" />
</element>
b
<element type="quadricpart" label="b">
    <objColor r="216" g="27" b="96" alpha="0.2" />
    <layer val="0" />
    <labelMode val="0" />
    <lineStyle thickness="5" type="0" typeHidden="1" />
</element>
c
<element type="conic3d" label="c">
    <objColor r="216" g="27" b="96" alpha="0.0" />
    <layer val="0" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="1" />
</element>
d
<element type="conic3d" label="d">
    <objColor r="216" g="27" b="96" alpha="0.0" />
    <layer val="0" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="1" />
</element>
O
<element type="point" label="O">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="0" />
    <labelMode val="0" />
    <coordStyle style="cartesian" />
</element>
e
<element type="conic3d" label="e">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="1" />
</element>
Q
<element type="point3d" label="Q">
    <objColor r="21" g="101" b="192" alpha="0.0" />
    <layer val="3" />
    <labelOffset x="3.0" y="2.0" />
    <labelMode val="0" />
</element>
p
<element type="plane3d" label="p">
    <objColor r="99" g="219" b="219" alpha="0.2" />
    <layer val="3" />
    <labelMode val="0" />
    <fading val="0.10000000149011612" />
    <lineStyle thickness="0" type="0" typeHidden="1" />
</element>
f
<element type="conic3dpart" label="f">
    <objColor r="21" g="101" b="192" alpha="0.10000000149011612" />
    <layer val="3" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
</element>
P
<element type="point3d" label="P">
    <objColor r="21" g="101" b="192" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
</element>
xzPlane
list.index(x): x not in list
l1
list.index(x): x not in list
A
<element type="point3d" label="A">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
</element>
C
<element type="point3d" label="C">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
</element>
l3
list.index(x): x not in list
B
<element type="point3d" label="B">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
</element>
D
<element type="point3d" label="D">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
</element>
a_1
<element type="line3d" label="a_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
c_1
<element type="conic3d" label="c_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
l_{10}
list.index(x): x not in list
l_{11}
list.index(x): x not in list
l10
list.index(x): x not in list
l_{12}
list.index(x): x not in list
l_{13}
list.index(x): x not in list
l11
list.index(x): x not in list
l_{14}
list.index(x): x not in list
l_{15}
list.index(x): x not in list
O''
<element type="point3d" label="O''">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
</element>
O'''
<element type="point3d" label="O'''">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
</element>
f_2
<element type="line3d" label="f_2">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
f_1
<element type="line3d" label="f_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
F_2
<element type="point3d" label="F_2">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
</element>
F_1
<element type="point3d" label="F_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
</element>
g
<element type="segment3d" label="g">
    <objColor r="255" g="0" b="0" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
l2
list.index(x): x not in list
C'
<element type="point3d" label="C'">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
</element>
A'
<element type="point3d" label="A'">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="3" />
    <labelMode val="0" />
</element>
i
<element type="segment3d" label="i">
    <objColor r="0" g="0" b="255" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
j
<element type="segment3d" label="j">
    <objColor r="0" g="0" b="255" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
h
<element type="segment3d" label="h">
    <objColor r="51" g="153" b="0" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="20" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
i_1
<element type="segment3d" label="i_1">
    <objColor r="255" g="0" b="0" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
j_1
<element type="segment3d" label="j_1">
    <objColor r="0" g="0" b="255" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
k_1
<element type="segment3d" label="k_1">
    <objColor r="51" g="153" b="0" alpha="0.0" />
    <layer val="5" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="20" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
k
<element type="conic3dpart" label="k">
    <objColor r="21" g="101" b="192" alpha="0.10000000149011612" />
    <layer val="1" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
</element>
q
<element type="plane3d" label="q">
    <objColor r="99" g="219" b="219" alpha="0.1" />
    <layer val="3" />
    <labelMode val="0" />
    <fading val="0.10000000149011612" />
    <lineStyle thickness="0" type="0" typeHidden="1" />
</element>
r
<element type="segment3d" label="r">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
s
<element type="segment3d" label="s">
    <objColor r="0" g="0" b="0" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
g_1
<element type="segment3d" label="g_1">
    <objColor r="255" g="0" b="0" alpha="0.0" />
    <layer val="6" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
r_1
<element type="segment3d" label="r_1">
    <objColor r="51" g="153" b="0" alpha="0.0" />
    <layer val="6" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="20" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
b_1
<element type="segment3d" label="b_1">
    <objColor r="255" g="0" b="0" alpha="0.0" />
    <layer val="6" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
o
<element type="quadric" label="o">
    <objColor r="211" g="47" b="47" alpha="0.1" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="5" type="0" typeHidden="1" />
</element>
u_{1}
<element type="quadric" label="u_{1}">
    <objColor r="211" g="47" b="47" alpha="0.1" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="5" type="0" typeHidden="1" />
</element>
p_1
<element type="plane3d" label="p_1">
    <objColor r="99" g="219" b="219" alpha="0.5" />
    <layer val="7" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <fading val="0.10000000149011612" />
    <lineStyle thickness="0" type="0" typeHidden="1" />
</element>
q_1
<element type="plane3d" label="q_1">
    <objColor r="99" g="219" b="219" alpha="0.5" />
    <layer val="7" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <fading val="0.10000000149011612" />
    <lineStyle thickness="0" type="0" typeHidden="1" />
</element>
d_1
<element type="conic3dpart" label="d_1">
    <objColor r="21" g="101" b="192" alpha="0.10000000149011612" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
</element>
e_1
<element type="conic3dpart" label="e_1">
    <objColor r="21" g="101" b="192" alpha="0.10000000149011612" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
</element>
l_1
<element type="line3d" label="l_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
l7
list.index(x): x not in list
l8
list.index(x): x not in list
P''
<element type="point3d" label="P''">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="7" />
    <labelMode val="0" />
</element>
P'''
<element type="point3d" label="P'''">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="7" />
    <labelMode val="0" />
</element>
l
<element type="segment3d" label="l">
    <objColor r="255" g="127" b="0" alpha="0.0" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="10" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
m
<element type="segment3d" label="m">
    <objColor r="255" g="255" b="102" alpha="0.0" />
    <layer val="7" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="10" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
n_2
<element type="segment3d" label="n_2">
    <objColor r="255" g="127" b="0" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="10" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
n_1
<element type="segment3d" label="n_1">
    <objColor r="255" g="255" b="102" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <lineStyle thickness="8" type="10" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
h_1
<element type="line3d" label="h_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="4" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
k_2
<element type="segment3d" label="k_2">
    <objColor r="255" g="204" b="102" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
P_{c}
<element type="point3d" label="P_{c}">
    <objColor r="0" g="0" b="255" alpha="0.0" />
    <layer val="1" />
    <labelMode val="0" />
</element>
h_2
<element type="line3d" label="h_2">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="2" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
P_{h}
<element type="point3d" label="P_{h}">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="2" />
    <labelMode val="0" />
</element>
h_3
<element type="line3d" label="h_3">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="2" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="1" type="0" typeHidden="2" />
</element>
P_{w}
<element type="point3d" label="P_{w}">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="2" />
    <labelMode val="0" />
</element>
u
<element type="vector3d" label="u">
    <objColor r="0" g="0" b="255" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <startPoint exp="P_{h}" />
</element>
v
<element type="vector3d" label="v">
    <objColor r="255" g="0" b="0" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <startPoint exp="P_{h}" />
</element>
n
<element type="vector3d" label="n">
    <objColor r="255" g="0" b="0" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <startPoint exp="P_{h}" />
</element>
t
<element type="line3d" label="t">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
    <lineStyle thickness="1" type="0" typeHidden="1" />
</element>
t_1
<element type="segment3d" label="t_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="9" />
    <labelMode val="3" />
    <caption val="$h$" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
j_2
<element type="segment3d" label="j_2">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="9" />
    <labelMode val="3" />
    <caption val="$w$" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>
l9
list.index(x): x not in list
E
<element type="point3d" label="E">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
</element>
F
<element type="point3d" label="F">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="8" />
    <labelMode val="0" />
    <auxiliary val="true" />
</element>
s_1
<element type="segment3d" label="s_1">
    <objColor r="110" g="109" b="115" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <lineStyle thickness="2" type="0" typeHidden="2" />
    <outlyingIntersections val="false" />
    <keepTypeOnTransform val="true" />
</element>