# Parsing object dependency using NetworkX

In [1]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

In [2]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

In [3]:
import networkx as nx
import polars as pl
import xml.etree.ElementTree as ET
import xmlschema

In [4]:
from ggblab import GeoGebra
# from ggblab.parser import tokenize_with_commas

In [79]:
# initialize base class, not open GeoGebra Widget
ggb = GeoGebra()

Using local cached file: xsd/common.xsd

In [86]:
# import sys
# from pathlib import Path
# sys.path.insert(0, str(Path.cwd().parent))

from ggblab_extra.dataframe_io import DataFrameIO

In [81]:
await ggb.init()

In [ ]:
c = ggb.construction.load('2025_13_01.ggb')

In [103]:
import xml.etree.ElementTree as ET
root = ET.Element(c.geogebra_xml)
tree = ET.ElementTree(root)
tree.write("2025_13_01.xml", encoding='utf-8', xml_declaration=True)

In [82]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [93]:
p.df = await DataFrameIO.initialize_dataframe(ggb, file='2025_13_01.ggb', _columns=p.COLUMNS + ["ShowObject", "ShowLabel", "Auxiliary"])
p.df2 = await DataFrameIO.initialize_dataframe(ggb, use_applet=True)

In [14]:
from ggblab_extra import ggb_parser

In [92]:
p.COLUMNS + ["ShowObject", "ShowLabel", "Auxiliary"]

['Type',
 'Command',
 'Value',
 'Caption',
 'Layer',
 'ShowObject',
 'ShowLabel',
 'Auxiliary']

In [66]:
r = await ggb.function("getAllObjectNames")
r

['C',
 'A',
 'poly1',
 'f',
 'g',
 'E',
 'D',
 'h',
 'i',
 'O',
 'c_1',
 'P',
 'j',
 'k',
 'l',
 'm',
 'n',
 'p',
 'q',
 'r',
 'poly2',
 's',
 't',
 'G',
 'H',
 'a_{3}',
 'b_1',
 'e',
 "P'",
 'd',
 'B',
 'f_1',
 'g_{4}',
 'w',
 'c_{5}',
 'I',
 'J',
 'K',
 'u',
 'v',
 'h_1',
 'L',
 'proj_{u}w',
 'proj_{v}w',
 'γ',
 'β',
 'α',
 'θ',
 'b',
 'c',
 "Γ'_{uu}",
 'Γ_{uu}',
 'u_1',
 'v_1',
 'δ',
 'ε',
 'text1',
 'text3',
 'text3_{1}',
 'text5',
 'i_1',
 't1',
 'p_1',
 'o',
 'c_3',
 't2',
 'p_2',
 'o_1',
 'a_1',
 't3',
 'p_3',
 'a_2',
 'c_4',
 'poly3',
 'j_1',
 'k_1',
 'F',
 'M',
 'l_1',
 'm_1',
 'poly4',
 'n_1',
 'q_1',
 'N',
 'Q',
 'r_1',
 's_1',
 't_1',
 'd_1',
 'e_1',
 'f_2',
 'g_{5}',
 'h_2',
 'a',
 'poly5',
 'i_2',
 'j_2',
 'R',
 'S',
 'k_2',
 'l_2',
 'poly6',
 'm_2',
 'n_2',
 'T',
 'U',
 'q_2',
 'r_2',
 "w'",
 't4',
 'c_2',
 'a_4',
 'b_2',
 'text4',
 's_2',
 't_2',
 'V',
 'poly7',
 'd_2',
 'e_2',
 'W',
 'Z',
 'f_3',
 'g_{6}',
 'text3_{2}',
 'text5_{1}',
 'h_3',
 "O'",
 'g_2',
 'g_1',
 't5',
 'i_3',
 'p_4',
 'c_6',
 't6',
 'j_3',
 'a_5',
 'p_5',
 'g_3',
 'text2',
 'ζ',
 'd_3',
 'A_1',
 'k_3',
 'r_3',
 'poly8',
 'm_3',
 't_3',
 'H_1',
 'I_1',
 'f_4',
 'h_4',
 'l_3',
 'B_1',
 'C_1',
 'q1',
 'a_6',
 "o'",
 'n_3',
 'q_3',
 't7',
 's_3',
 'a_7',
 'f_5',
 't8',
 'b_3',
 'p_6',
 'e_3',
 'text5_{3}',
 'η']

In [71]:
set(p.df2["Type"].unique()) - set(p.df["Type"].unique())

{'circle', 'quadrilateral', 'triangle'}

In [72]:
set(p.df["Type"].unique()) - set(p.df2["Type"].unique())

{'conic'}

In [98]:
import os
os.path.splitext(ggb.file.source_file)[0]+'.json'

'2025_13_01.json'

In [100]:
p.df.write_json(os.path.splitext(ggb.file.source_file)[0]+'.json')

In [62]:
# p.df2["Command"] == p.df["Command"]
mask = p.df['Command'].eq_missing(p.df2['Command']).not_()
p.df2.filter(mask)

shape: (51, 6)
┌───────────┬─────────┬──────────────────────────┬──────────────────────────┬──────────────┬───────┐
│ Name      ┆ Type    ┆ Command                  ┆ Value                    ┆ Caption      ┆ Layer │
│ ---       ┆ ---     ┆ ---                      ┆ ---                      ┆ ---          ┆ ---   │
│ str       ┆ str     ┆ str                      ┆ str                      ┆ str          ┆ i64   │
╞═══════════╪═════════╪══════════════════════════╪══════════════════════════╪══════════════╪═══════╡
│ E         ┆ point   ┆ Polygon(C, A, 4)         ┆ E = (2.1, 2.2)           ┆ null         ┆ 2     │
│ D         ┆ point   ┆ Polygon(C, A, 4)         ┆ D = (0, 2.2)             ┆ null         ┆ 2     │
│ h         ┆ segment ┆ Segment(E, D, poly1)     ┆ h = 2.2                  ┆ null         ┆ 2     │
│ i         ┆ segment ┆ Segment(D, C, poly1)     ┆ i = 2.2                  ┆ null         ┆ 2     │
│ G         ┆ point   ┆ Polygon(A, C, 4)         ┆ G = (0, -2.2)            ┆ null         ┆ 4     │
│ H         ┆ point   ┆ Polygon(A, C, 4)         ┆ H = (2.2, -2.1)          ┆ null         ┆ 4     │
│ a_{3}     ┆ segment ┆ Segment(G, H, poly2)     ┆ a_{3} = 2.2              ┆ null         ┆ 4     │
│ b_1       ┆ segment ┆ Segment(H, A, poly2)     ┆ b_1 = 2.2                ┆ null         ┆ 4     │
│ proj_{u}w ┆ numeric ┆ (w u) / (u u)            ┆ proj_{u}w = 1.2          ┆ null         ┆ 8     │
│ proj_{v}w ┆ numeric ┆ (w v) / (v v)            ┆ proj_{v}w = 0.8          ┆ null         ┆ 8     │
│ Γ'_{uu}   ┆ numeric ┆ -((proj_{u}w cos(θ) -    ┆ Γ'_{uu} = 1.9            ┆ null         ┆ 8     │
│           ┆         ┆ proj_{v}…                ┆                          ┆              ┆       │
│ Γ_{uu}    ┆ numeric ┆ (proj_{u}w - proj_{v}w   ┆ Γ_{uu} = 2.2             ┆ null         ┆ 8     │
│           ┆         ┆ cos(θ))…                 ┆                          ┆              ┆       │
│ u_1       ┆ vector  ┆ Translate((u w) / (u u)  ┆ u_1 = (1.2, 0)           ┆ $proj_{u} w$ ┆ 7     │
│           ┆         ┆ u, C)                    ┆                          ┆              ┆       │
│ v_1       ┆ vector  ┆ Translate((w v) / (v v)  ┆ v_1 = (-0.4, 0.7)        ┆ $proj_{v} w$ ┆ 7     │
│           ┆         ┆ v, P')                   ┆                          ┆              ┆       │
│ text1     ┆ text    ┆ null                     ┆ 1.  Thales's  theorem:   ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ right  …                 ┆              ┆       │
│ text3     ┆ text    ┆ null                     ┆ 3.  Pythagorean  theorem ┆ null         ┆ 9     │
│ text3_{1} ┆ text    ┆ null                     ┆ $\|a\| = \|b\|           ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ \cos(\gamma)+ \…         ┆              ┆       │
│ text5     ┆ text    ┆ null                     ┆ 5.  Projection           ┆ null         ┆ 9     │
│ F         ┆ point   ┆ Polygon(C, P, 4)         ┆ F = (-0.3, 1.8)          ┆ null         ┆ 4     │
│ M         ┆ point   ┆ Polygon(C, P, 4)         ┆ M = (-1, 0.7)            ┆ null         ┆ 4     │
│ l_1       ┆ segment ┆ Segment(F, M, poly3)     ┆ l_1 = 1.3                ┆ null         ┆ 4     │
│ m_1       ┆ segment ┆ Segment(M, C, poly3)     ┆ m_1 = 1.3                ┆ null         ┆ 4     │
│ N         ┆ point   ┆ Polygon(P, A, 4)         ┆ N = (3.2, 1.5)           ┆ null         ┆ 4     │
│ Q         ┆ point   ┆ Polygon(P, A, 4)         ┆ Q = (1.7, 2.5)           ┆ null         ┆ 4     │
│ r_1       ┆ segment ┆ Segment(N, Q, poly4)     ┆ r_1 = 1.7                ┆ null         ┆ 4     │
│ s_1       ┆ segment ┆ Segment(Q, P, poly4)     ┆ s_1 = 1.7                ┆ null         ┆ 4     │
│ R         ┆ point   ┆ Polygon(C, B, 4)         ┆ R = (-0.5, 2.8)          ┆ null         ┆ 4     │
│ S         ┆ point   ┆ Polygon(C, B, 4)         ┆ S = (-1.6, 1.2)          ┆ null         ┆ 4     │
│ k_2       ┆ segment ┆ Segment(R, S, poly5)     ┆ k_2 = 2                  ┆ null         ┆ 4     │
│ l_2       ┆ segment ┆ Segment(S, C, poly5)     ┆ l_2 = 2                  ┆ null         ┆ 4     │
│ T         ┆ point   ┆ Polygon(B, A, 4)         ┆ T = (3.8, 1)             ┆ null         ┆ 4     │
│ U         ┆ point   ┆ Polygon(B, A, 4)         ┆ U = (2.8, 2.6)           ┆ null         ┆ 4     │
│ q_2       ┆ segment ┆ Segment(T, U, poly6)     ┆ q_2 = 1.9                ┆ null         ┆ 4     │
│ r_2       ┆ segment ┆ Segment(U, B, poly6)     ┆ r_2 = 1.9                ┆ null         ┆ 4     │
│ w'        ┆ vector  ┆ Translate(Γ_{uu} u +     ┆ w' = (1.2, 1.6)          ┆ null         ┆ 7     │
│           ┆         ┆ Γ'_{uu} v…               ┆                          ┆              ┆       │
│ text4     ┆ text    ┆ null                     ┆ 4.  Orthocenter  and     ┆ null         ┆ 9     │
│           ┆         ┆                          ┆  Law  of …               ┆              ┆       │
│ W         ┆ point   ┆ Polygon(V, M, 4)         ┆ W = (1.4, -1)            ┆ null         ┆ 4     │
│ Z         ┆ point   ┆ Polygon(V, M, 4)         ┆ Z = (3.2, 1.5)           ┆ null         ┆ 4     │
│ f_3       ┆ segment ┆ Segment(W, Z, poly7)     ┆ f_3 = 3                  ┆ null         ┆ 4     │
│ g_{6}     ┆ segment ┆ Segment(Z, V, poly7)     ┆ g_{6} = 3                ┆ null         ┆ 4     │
│ text3_{2} ┆ text    ┆ null                     ┆ $\|a\|^2 = \|b\|^2 +     ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ \|c\|^2 -…               ┆              ┆       │
│ text5_{1} ┆ text    ┆ null                     ┆ $\|b\| \cos(\theta) =    ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ \frac{\v…                ┆              ┆       │
│ g_2       ┆ numeric ┆ Distance(P, O') /        ┆ g_2 = 1.4                ┆ null         ┆ 8     │
│           ┆         ┆ Distance(C, …            ┆                          ┆              ┆       │
│ g_1       ┆ numeric ┆ Distance(A, O') /        ┆ g_1 = 1.4                ┆ null         ┆ 8     │
│           ┆         ┆ Distance(P, …            ┆                          ┆              ┆       │
│ g_3       ┆ numeric ┆ Area(t5) g_2 g_2         ┆ g_3 = 0.7                ┆ null         ┆ 8     │
│ text2     ┆ text    ┆ null                     ┆ 2.  Geometric  mean      ┆ null         ┆ 9     │
│ H_1       ┆ point   ┆ Polygon(O', P, 4)        ┆ H_1 = (-0.3, 1)          ┆ null         ┆ 2     │
│ I_1       ┆ point   ┆ Polygon(O', P, 4)        ┆ I_1 = (-0.3, 0)          ┆ null         ┆ 2     │
│ f_4       ┆ segment ┆ Segment(H_1, I_1, poly8) ┆ f_4 = 1                  ┆ null         ┆ 2     │
│ h_4       ┆ segment ┆ Segment(I_1, O', poly8)  ┆ h_4 = 1                  ┆ null         ┆ 2     │
│ text5_{3} ┆ text    ┆ null                     ┆ $proj_{\vec{a}}\ \vec{b} ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ = \fr…                   ┆              ┆       │
└───────────┴─────────┴──────────────────────────┴──────────────────────────┴──────────────┴───────┘

In [63]:
p.df.filter(mask)

shape: (51, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ h         ┆ segment ┆ Segment(E,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ D, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ i         ┆ segment ┆ Segment(D,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ E         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ D         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_{3}     ┆ segment ┆ Segment(G,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ H, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ b_1       ┆ segment ┆ Segment(H,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ G         ┆ point   ┆ Polygon(A,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ H         ┆ point   ┆ Polygon(A,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ proj_{u}w ┆ numeric ┆ ((w * u)) / ┆ ((w * u)) / ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ((u * u))   ┆ ((u * u))   ┆   ┆       ┆            ┆           ┆           │
│ proj_{v}w ┆ numeric ┆ ((w * v)) / ┆ ((w * v)) / ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ((v * v))   ┆ ((v * v))   ┆   ┆       ┆            ┆           ┆           │
│ Γ'_{uu}   ┆ numeric ┆ (-(((proj_{ ┆ (-(((proj_{ ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ u}w *       ┆ u}w *       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ cos(θ)) -   ┆ cos(θ)) -   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ pro…        ┆ pro…        ┆   ┆       ┆            ┆           ┆           │
│ Γ_{uu}    ┆ numeric ┆ (proj_{u}w  ┆ (proj_{u}w  ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ -           ┆ -           ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ (proj_{v}w  ┆ (proj_{v}w  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * cos(…     ┆ * cos(…     ┆   ┆       ┆            ┆           ┆           │
│ u_1       ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ ector((((u  ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * w)) / …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ v_1       ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ ector((((w  ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * v)) / …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ text1     ┆ text    ┆ "1.         ┆ "1.         ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│           ┆         ┆  Thales's   ┆  Thales's   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  theorem:   ┆  theorem:   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ right …     ┆ right …     ┆   ┆       ┆            ┆           ┆           │
│ text3     ┆ text    ┆ "3.  Pythag ┆ "3.  Pythag ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ orean       ┆ orean       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  theorem"   ┆  theorem"   ┆   ┆       ┆            ┆           ┆           │
│ text3_{1} ┆ text    ┆ "$\|a\| =   ┆ "$\|a\| =   ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ \|b\| \cos( ┆ \|b\| \cos( ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \gamma)+ …  ┆ \gamma)+ …  ┆   ┆       ┆            ┆           ┆           │
│ text5     ┆ text    ┆ "5.  Projec ┆ "5.  Projec ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ tion"       ┆ tion"       ┆   ┆       ┆            ┆           ┆           │
│ l_1       ┆ segment ┆ Segment(F,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ M, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ m_1       ┆ segment ┆ Segment(M,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ F         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ M         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ r_1       ┆ segment ┆ Segment(N,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ Q, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ s_1       ┆ segment ┆ Segment(Q,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ N         ┆ point   ┆ Polygon(P,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ Q         ┆ point   ┆ Polygon(P,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ k_2       ┆ segment ┆ Segment(R,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ S, poly5)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ l_2       ┆ segment ┆ Segment(S,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly5)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ R         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ B, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ S         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ B, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ q_2       ┆ segment ┆ Segment(T,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ U, poly6)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ r_2       ┆ segment ┆ Segment(U,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ B, poly6)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ T         ┆ point   ┆ Polygon(B,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ U         ┆ point   ┆ Polygon(B,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ w'        ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ector((Γ_{u ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ u} * u) …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ text4     ┆ text    ┆ "4.  Orthoc ┆ "4.  Orthoc ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ enter  and  ┆ enter  and  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  Law  of…   ┆  Law  of…   ┆   ┆       ┆            ┆           ┆           │
│ f_3       ┆ segment ┆ Segment(W,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ Z, poly7)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ g_{6}     ┆ segment ┆ Segment(Z,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ V, poly7)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ W         ┆ point   ┆ Polygon(V,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ M, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ Z         ┆ point   ┆ Polygon(V,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ M, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ text3_{2} ┆ text    ┆ "$\|a\|^2 = ┆ "$\|a\|^2 = ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ \|b\|^2 +   ┆ \|b\|^2 +   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \|c\|^2 …   ┆ \|c\|^2 …   ┆   ┆       ┆            ┆           ┆           │
│ text5_{1} ┆ text    ┆ "$\|b\| \co ┆ "$\|b\| \co ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ s(\theta) = ┆ s(\theta) = ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \frac{\…    ┆ \frac{\…    ┆   ┆       ┆            ┆           ┆           │
│ g_2       ┆ numeric ┆ Distance[P, ┆ Distance[P, ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ O'] /       ┆ O'] /       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Distance[C, ┆ Distance[C, ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ …           ┆ …           ┆   ┆       ┆            ┆           ┆           │
│ g_1       ┆ numeric ┆ Distance[A, ┆ Distance[A, ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ O'] /       ┆ O'] /       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Distance[P, ┆ Distance[P, ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ …           ┆ …           ┆   ┆       ┆            ┆           ┆           │
│ g_3       ┆ numeric ┆ ((Area[t5]  ┆ ((Area[t5]  ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ * g_2) *    ┆ * g_2) *    ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ g_2)        ┆ g_2)        ┆   ┆       ┆            ┆           ┆           │
│ text2     ┆ text    ┆ "2.         ┆ "2.         ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆  Geometric  ┆  Geometric  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  mean"      ┆  mean"      ┆   ┆       ┆            ┆           ┆           │
│ f_4       ┆ segment ┆ Segment(H_1 ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , I_1,      ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ poly8)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_4       ┆ segment ┆ Segment(I_1 ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , O',       ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ poly8)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ H_1       ┆ point   ┆ Polygon(O', ┆ null        ┆ … ┆ 2     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ I_1       ┆ point   ┆ Polygon(O', ┆ null        ┆ … ┆ 2     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ text5_{3} ┆ text    ┆ "$proj_{\ve ┆ "$proj_{\ve ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ c{a}}\      ┆ c{a}}\      ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \vec{b} =   ┆ \vec{b} =   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \f…         ┆ \f…         ┆   ┆       ┆            ┆           ┆           │
└───────────┴─────────┴─────────────┴─────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [7]:
# load from .ggb (zipped, and base64 encoded)
c = ggb.construction.load('2025_13_01.ggb')
# c = ggb.construction.load('2025_06_08.ggb')
# c = ggb.construction.load('2025_15_01.ggb')

In [22]:
# parse loaded xml as python dict
o = c.ggb_schema.decode(c.geogebra_xml)

In [23]:
# check command part in archive file, and found not enough information for construction...
for _c in o["command"]:
    _ci = tuple(zip(*_c['input'].items()))[1]
    _co = tuple(zip(*_c['output'].items()))[1]
    print(f"{', '.join(_co)} = {_c['@name']}[{', '.join(_ci)}]")

poly1, f, g, h, i, E, D = Polygon[C, A, 4]
O = Midpoint[C, A]
c_1 = Circle[O, C]
P = Point[c_1]
j = Ray[C, P]
k = Ray[A, P]
l = OrthogonalLine[E, k]
m = OrthogonalLine[D, j]
n = Line[D, j]
p = Line[E, m]
q = Line[A, l]
r = Line[C, k]
poly2, s, t, a_{3}, b_1, G, H = Polygon[A, C, 4]
e = Ray[C, A]
P' = Point[c_1]
d = Ray[A, P']
B = Intersect[d, j]
f_1 = Line[C, d]
g_{4} = OrthogonalLine[C, d]
w = Vector[C, B]
c_{5} = Circle[C, 1]
I,  = Intersect[c_{5}, e]
J, K = Intersect[c_{5}, f_1]
u = Vector[C, I]
v = Vector[C, K]
h_1 = OrthogonalLine[B, e]
L = Intersect[h_1, e]
γ = Angle[A, C, B]
β = Angle[A, B, C]
α = Angle[C, A, B]
θ = Angle[Vector[C, A], Vector[A, B]]
b = Distance[C, A]
c = Distance[A, B]
u_1 = Translate[Vector[(((u * w)) / ((u * u)) * u)], C]
v_1 = Translate[Vector[(((w * v)) / ((v * v)) * v)], P']
δ = Angle[C, P, A]
ε = Angle[C, P', A]
i_1 = Segment[P, O]
t1, p_1, o, c_3 = Polygon[O, C, P]
t2, p_2, o_1, a_1 = Polygon[O, A, P]
t3, p_3, a_2, c_4 = Polygon[A, C, P]
poly3, j_1, k_1, l_1, m_1, F, M = Polygon[C, P, 4]
poly4, n_1, q_1, r_1, s_1, N, Q = Polygon[P, A, 4]
t_1 = Segment[C, L]
d_1 = Segment[A, L]
e_1 = Segment[C, P]
f_2 = Segment[B, P]
g_{5} = Segment[B, P']
h_2 = Segment[A, P']
a = Distance[B, C]
poly5, i_2, j_2, k_2, l_2, R, S = Polygon[C, B, 4]
poly6, m_2, n_2, q_2, r_2, T, U = Polygon[B, A, 4]
w' = Translate[Vector[(Γ_{uu} * u) + (Γ'_{uu} * v)], C]
t4, c_2, a_4, b_2 = Polygon[A, B, C]
s_2 = Segment[O, C]
t_2 = Segment[O, A]
V = Intersect[n, p]
poly7, d_2, e_2, f_3, g_{6}, W, Z = Polygon[V, M, 4]
h_3 = OrthogonalLine[P, e]
O' = Intersect[h_3, e]
t5, i_3, p_4, c_6 = Polygon[P, C, O']
t6, j_3, a_5, p_5 = Polygon[A, P, O']
ζ = Angle[P, O', C]
d_3 = Circle[O', C]
A_1 = Intersect[d_3, h_3, 1]
k_3 = Line[A_1, e]
r_3 = OrthogonalLine[A, k_3]
poly8, m_3, t_3, f_4, h_4, H_1, I_1 = Polygon[O', P, 4]
l_3 = Line[A_1, e]
B_1 = Intersect[l_3, Line[P, A]]
C_1 = Intersect[l_3, r_3]
q1, a_6, o', n_3, q_3 = Polygon[A, O', A_1, C_1]
t7, s_3, a_7, f_5 = Polygon[A, F, I_1]
t8, b_3, p_6, e_3 = Polygon[P, B_1, A_1]
η = Angle[C, A, B]

## with Applet

In [10]:
r = await ggb.init()
r

Warning: Could not refresh object cache: 'NoneType' object has no attribute 'send'

In [11]:
# ggb.construction.base64_buffer.decode('utf-8')

In [12]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [13]:
ggb.comm.target_comm

In [14]:
# compare in archive and in applet
for _c in o["command"]:
    _ci = tuple(zip(*_c['input'].items()))[1]
    _co = tuple(zip(*_c['output'].items()))[1]
    c1 = (f"{_c['@name']}({', '.join(_ci)})"
          .replace('OrthogonalLine', 'PerpendicularLine')
          .translate(str.maketrans('[]', '()')))
    c2 = await ggb.function("getCommandString", [_c['output']['@a0']])
    if (c1 != c2):
        # print(f"{', '.join(_co)} = {c1}")
        print(f"{_c['output']['@a0']}: {c1}, {c2}")

u_1: Translate(Vector((((u * w)) / ((u * u)) * u)), C), Translate((u w) / (u u) u, C)
v_1: Translate(Vector((((w * v)) / ((v * v)) * v)), P'), Translate((w v) / (v v) v, P')
w': Translate(Vector((Γ_{uu} * u) + (Γ'_{uu} * v)), C), Translate(Γ_{uu} u + Γ'_{uu} v, C)

In [15]:
for _e in o["expression"]:
    c1 = (_e['@exp']
          .translate(str.maketrans('[]', '()')))
    c2 = await ggb.function("getCommandString", [_e['@label']])
    if (c1 != c2):
        print(_e['@label'], c1, c2)

proj_{u}w ((w * u)) / ((u * u)) (w u) / (u u)
proj_{v}w ((w * v)) / ((v * v)) (w v) / (v v)
Γ'_{uu} (-(((proj_{u}w * cos(θ)) - proj_{v}w) / (sin(θ))^(2))) -((proj_{u}w cos(θ) - proj_{v}w) / sin²(θ))
Γ_{uu} (proj_{u}w - (proj_{v}w * cos(θ))) / (sin(θ))^(2) (proj_{u}w - proj_{v}w cos(θ)) / sin²(θ)
text1 "1.  Thales's  theorem: right  triangle  inscribed  in  a  circle" None
text3 "3.  Pythagorean  theorem" None
text3_{1} "$\|a\| = \|b\| \cos(\gamma)+ \|c\| \cos(\beta)$
$\|b\| = \|c\| \cos(\alpha) + \|a\| \cos(\gamma)$
$\|c\| = \|a\| \cos(\beta) + \|b\| \cos(\alpha)$" None
text5 "5.  Projection" None
text4 "4.  Orthocenter  and  Law  of  cosines" None
text3_{2} "$\|a\|^2 = \|b\|^2 + \|c\|^2 - 2 \|b\|\|c\| \cos(\alpha)$
$\|b\|^2 = \|c\|^2 + \|a\|^2 - 2 \|c\|\|a\| \cos(\beta)$
$\|c\|^2 = \|a\|^2 + \|b\|^2 - 2 \|a\|\|b\| \cos(\gamma)$" None
text5_{1} "$\|b\| \cos(\theta) = \frac{\vec{b}\cdot\vec{a}}{\vec{a}\cdot\vec{a}}$" None
g_3 ((Area(t5) * g_2) * g_2) Area(t5) g_2 g_2
text2 "2.  Geometric  mean" None
text5_{3} "$proj_{\vec{a}}\ \vec{b} = \frac{\vec{b}\cdot\vec{a}}{\vec{a}\cdot\vec{a}}\ \vec{a}$" None

In [160]:
# construction protocol as list
def dummy():
    for e in o['element']:
        _n = e['@label']
        cmd = None
        exp = None
        for _c in o['command']:
            _ci = tuple(zip(*_c['input'].items()))[1]
            _co = tuple(zip(*_c['output'].items()))[1]
            def build_command_string(edges, vertices):
                nonlocal _n
                nonlocal _ci, _co
                nonlocal cmd, ci , co
                try:
                    _i = edges.index(_n)
                    ci = (vertices[_i:] + vertices[:_i])[:2] + (_co[0],)
                    co = _co[0]
                    cmd = f"Segment({', '.join(ci)})"
                except:
                    pass
            if _n in _co:
                # print(_c['@name'], _ci, _co)
                if _c['@name'] == 'Polygon':
                    match _ci:
                        case (p0, p1, '4'):
                            _, e0, e1, e2, e4, p2, p3 = _co
                            edges = (e0, e1, e2, e4)
                            vertices = (p0, p1, p2, p3)
                            build_command_string(edges, vertices)
                            break
                        case _:
                            edges = _co[1:]
                            vertices = _ci
                            build_command_string(edges, vertices)             
                            break
                ci = _ci
                co = _co
                cmd = (f"{_c['@name']}({', '.join(_ci)})"
                      .replace('OrthogonalLine', 'PerpendicularLine')
                      .translate(str.maketrans('[]', '()')))
                break
        for _e in o['expression']:
            if _n == _e['@label']:
                exp = _e['@exp']
        
        # if (e['@type'] != 'text') and (cmd or exp):
        #     r = await ggb.function("getCommandString", [_n])
        #     if r != (cmd or exp):
        #         print(_n, e['@type'], cmd or exp, r)
        # r = await ggb.function("getValueString", [_n])
    
        print([_n, e['@type'], cmd or exp, 
               e.get('caption', [{}])[0].get('@val'),
               e.get('layer', [{}])[0].get('@val'),
               e.get('show', [{}])[0].get('@object'), 
               e.get('show', [{}])[0].get('@label'), 
               e.get('auxiliary', [{}])[0].get('@val'), 
              ])

dummy()

['C', 'point', None, None, 9, True, True, None]
['A', 'point', None, None, 9, True, True, None]
['poly1', 'polygon', None, None, 3, False, False, True]
['f', 'segment', 'Segment(C, A, poly1)', None, 2, False, False, True]
['g', 'segment', 'Segment(A, E, poly1)', None, 2, False, False, True]
['h', 'segment', 'Segment(E, D, poly1)', None, 2, False, False, True]
['i', 'segment', 'Segment(D, C, poly1)', None, 2, False, False, True]
['E', 'point', None, None, 2, True, False, True]
['D', 'point', None, None, 2, True, False, True]
['O', 'point', 'Midpoint(C, A)', None, 1, False, True, None]
['c_1', 'conic', 'Circle(O, C)', None, 0, True, False, True]
['P', 'point', 'Point(c_1)', None, 9, True, True, None]
['j', 'ray', 'Ray(C, P)', None, 0, True, False, None]
['k', 'ray', 'Ray(A, P)', None, 0, True, False, None]
['l', 'line', 'PerpendicularLine(E, k)', None, 3, False, False, True]
['m', 'line', 'PerpendicularLine(D, j)', None, 3, False, False, True]
['n', 'line', 'Line(D, j)', None, 3, False, False, None]
['p', 'line', 'Line(E, m)', None, 3, False, False, None]
['q', 'line', 'Line(A, l)', None, 3, False, False, None]
['r', 'line', 'Line(C, k)', None, 3, False, False, None]
['poly2', 'polygon', None, None, 3, False, False, None]
['s', 'segment', 'Segment(A, C, poly2)', None, 4, False, False, True]
['t', 'segment', 'Segment(C, G, poly2)', None, 4, False, False, True]
['a_{3}', 'segment', 'Segment(G, H, poly2)', None, 4, False, False, True]
['b_1', 'segment', 'Segment(H, A, poly2)', None, 4, False, False, True]
['G', 'point', None, None, 4, True, False, True]
['H', 'point', None, None, 4, True, False, True]
['e', 'ray', 'Ray(C, A)', None, 0, True, False, None]
["P'", 'point', 'Point(c_1)', None, 9, True, True, None]
['d', 'ray', "Ray(A, P')", None, 4, False, False, None]
['B', 'point', 'Intersect(d, j)', None, 4, False, True, None]
['f_1', 'line', 'Line(C, d)', None, 6, False, False, None]
['g_{4}', 'line', 'PerpendicularLine(C, d)', None, 4, False, False, None]
['w', 'vector', 'Vector(C, B)', '$w$', 7, False, True, None]
['c_{5}', 'conic', 'Circle(C, 1)', None, 6, False, False, None]
['I', 'point', 'Intersect(c_{5}, e)', None, 6, False, True, None]
['J', 'point', 'Intersect(c_{5}, f_1)', None, 7, False, True, True]
['K', 'point', 'Intersect(c_{5}, f_1)', None, 6, False, True, None]
['u', 'vector', 'Vector(C, I)', '$u$', 6, False, True, None]
['v', 'vector', 'Vector(C, K)', '$v$', 6, False, True, None]
['h_1', 'line', 'PerpendicularLine(B, e)', None, 4, False, False, None]
['L', 'point', 'Intersect(h_1, e)', None, 4, False, True, None]
['proj_{u}w', 'numeric', '((w * u)) / ((u * u))', None, None, None, None, None]
['proj_{v}w', 'numeric', '((w * v)) / ((v * v))', None, None, None, None, None]
['γ', 'angle', 'Angle(A, C, B)', None, 5, False, True, None]
['β', 'angle', 'Angle(A, B, C)', None, 5, False, True, None]
['α', 'angle', 'Angle(C, A, B)', None, 5, False, True, None]
['θ', 'angle', 'Angle(Vector(C, A), Vector(A, B))', '$\\theta$', 6, False, True, None]
['b', 'numeric', 'Distance(C, A)', None, None, None, None, None]
['c', 'numeric', 'Distance(A, B)', None, None, None, None, None]
["Γ'_{uu}", 'numeric', '(-(((proj_{u}w * cos(θ)) - proj_{v}w) / (sin(θ))^(2)))', None, None, None, None, None]
['Γ_{uu}', 'numeric', '(proj_{u}w - (proj_{v}w * cos(θ))) / (sin(θ))^(2)', None, None, None, None, None]
['u_1', 'vector', 'Translate(Vector((((u * w)) / ((u * u)) * u)), C)', '$proj_{u} w$', 7, False, True, None]
['v_1', 'vector', "Translate(Vector((((w * v)) / ((v * v)) * v)), P')", '$proj_{v} w$', 7, False, True, None]
['δ', 'angle', 'Angle(C, P, A)', None, 0, True, False, None]
['ε', 'angle', "Angle(C, P', A)", None, 4, False, False, None]
['text1', 'text', '"1. \xa0Thales\'s \xa0theorem: right \xa0triangle \xa0inscribed \xa0in \xa0a \xa0circle"', None, 9, True, False, None]
['text3', 'text', '"3. \xa0Pythagorean \xa0theorem"', None, 9, False, False, None]
['text3_{1}', 'text', '"$\\|a\\| = \\|b\\| \\cos(\\gamma)+ \\|c\\| \\cos(\\beta)$\n$\\|b\\| = \\|c\\| \\cos(\\alpha) + \\|a\\| \\cos(\\gamma)$\n$\\|c\\| = \\|a\\| \\cos(\\beta) + \\|b\\| \\cos(\\alpha)$"', None, 9, False, False, None]
['text5', 'text', '"5. \xa0Projection"', None, 9, False, False, None]
['i_1', 'segment', 'Segment(P, O)', None, 1, False, False, None]
['t1', 'polygon', None, None, 1, False, False, None]
['p_1', 'segment', 'Segment(O, C, t1)', None, 1, False, False, True]
['o', 'segment', 'Segment(C, P, t1)', None, 1, False, False, True]
['c_3', 'segment', 'Segment(P, O, t1)', None, 1, False, False, True]
['t2', 'polygon', None, None, 1, False, False, None]
['p_2', 'segment', 'Segment(O, A, t2)', None, 1, False, False, True]
['o_1', 'segment', 'Segment(A, P, t2)', None, 1, False, False, True]
['a_1', 'segment', 'Segment(P, O, t2)', None, 1, False, False, True]
['t3', 'polygon', None, None, 3, False, False, None]
['p_3', 'segment', 'Segment(A, C, t3)', None, 3, False, False, True]
['a_2', 'segment', 'Segment(C, P, t3)', None, 3, False, False, True]
['c_4', 'segment', 'Segment(P, A, t3)', None, 3, False, False, True]
['poly3', 'polygon', None, None, 3, False, False, None]
['j_1', 'segment', 'Segment(C, P, poly3)', None, 4, False, False, True]
['k_1', 'segment', 'Segment(P, F, poly3)', None, 4, False, False, True]
['l_1', 'segment', 'Segment(F, M, poly3)', None, 4, False, False, True]
['m_1', 'segment', 'Segment(M, C, poly3)', None, 4, False, False, True]
['F', 'point', None, None, 4, True, False, True]
['M', 'point', None, None, 4, True, False, True]
['poly4', 'polygon', None, None, 3, False, False, None]
['n_1', 'segment', 'Segment(P, A, poly4)', None, 4, False, False, True]
['q_1', 'segment', 'Segment(A, N, poly4)', None, 4, False, False, True]
['r_1', 'segment', 'Segment(N, Q, poly4)', None, 4, False, False, True]
['s_1', 'segment', 'Segment(Q, P, poly4)', None, 4, False, False, True]
['N', 'point', None, None, 4, True, False, True]
['Q', 'point', None, None, 4, True, False, True]
['t_1', 'segment', 'Segment(C, L)', '$\\|a\\| cos(\\gamma)$', 5, False, True, None]
['d_1', 'segment', 'Segment(A, L)', '$\\|c\\| \\cos(\\alpha)$', 5, False, True, None]
['e_1', 'segment', 'Segment(C, P)', '$\\|b\\| cos(\\gamma)$', 5, False, True, None]
['f_2', 'segment', 'Segment(B, P)', '$\\|c\\| cos(\\beta)$', 5, False, True, None]
['g_{5}', 'segment', "Segment(B, P')", '$\\|a\\| cos(\\beta)$', 5, False, True, None]
['h_2', 'segment', "Segment(A, P')", '$\\|b\\| cos(\\alpha)$', 5, False, True, None]
['a', 'numeric', 'Distance(B, C)', None, None, None, None, None]
['poly5', 'polygon', None, None, 5, False, False, None]
['i_2', 'segment', 'Segment(C, B, poly5)', None, 4, False, False, True]
['j_2', 'segment', 'Segment(B, R, poly5)', None, 4, False, False, True]
['k_2', 'segment', 'Segment(R, S, poly5)', None, 4, False, False, True]
['l_2', 'segment', 'Segment(S, C, poly5)', None, 4, False, False, True]
['R', 'point', None, None, 4, True, False, True]
['S', 'point', None, None, 4, True, False, True]
['poly6', 'polygon', None, None, 5, False, False, None]
['m_2', 'segment', 'Segment(B, A, poly6)', None, 4, False, False, True]
['n_2', 'segment', 'Segment(A, T, poly6)', None, 4, False, False, True]
['q_2', 'segment', 'Segment(T, U, poly6)', None, 4, False, False, True]
['r_2', 'segment', 'Segment(U, B, poly6)', None, 4, False, False, True]
['T', 'point', None, None, 4, True, False, True]
['U', 'point', None, None, 4, True, False, True]
["w'", 'vector', "Translate(Vector((Γ_{uu} * u) + (Γ'_{uu} * v)), C)", None, 7, False, False, None]
['t4', 'polygon', None, None, 4, False, False, None]
['c_2', 'segment', 'Segment(A, B, t4)', None, 4, False, False, True]
['a_4', 'segment', 'Segment(B, C, t4)', None, 4, False, False, True]
['b_2', 'segment', 'Segment(C, A, t4)', None, 4, False, False, True]
['text4', 'text', '"4. \xa0Orthocenter \xa0and \xa0Law \xa0of \xa0cosines"', None, 9, False, False, None]
['s_2', 'segment', 'Segment(O, C)', None, 1, False, False, None]
['t_2', 'segment', 'Segment(O, A)', None, 1, False, False, None]
['V', 'point', 'Intersect(n, p)', None, 4, True, False, True]
['poly7', 'polygon', None, None, 3, False, False, True]
['d_2', 'segment', 'Segment(V, M, poly7)', None, 4, False, False, True]
['e_2', 'segment', 'Segment(M, W, poly7)', None, 4, False, False, True]
['f_3', 'segment', 'Segment(W, Z, poly7)', None, 4, False, False, True]
['g_{6}', 'segment', 'Segment(Z, V, poly7)', None, 4, False, False, True]
['W', 'point', None, None, 4, True, False, True]
['Z', 'point', None, None, 4, True, False, True]
['text3_{2}', 'text', '"$\\|a\\|^2 = \\|b\\|^2 + \\|c\\|^2 - 2 \\|b\\|\\|c\\| \\cos(\\alpha)$\n$\\|b\\|^2 = \\|c\\|^2 + \\|a\\|^2 - 2 \\|c\\|\\|a\\| \\cos(\\beta)$\n$\\|c\\|^2 = \\|a\\|^2 + \\|b\\|^2 - 2 \\|a\\|\\|b\\| \\cos(\\gamma)$"', None, 9, False, False, None]
['text5_{1}', 'text', '"$\\|b\\| \\cos(\\theta) = \\frac{\\vec{b}\\cdot\\vec{a}}{\\vec{a}\\cdot\\vec{a}}$"', None, 9, False, False, None]
['h_3', 'line', 'PerpendicularLine(P, e)', None, 2, False, False, True]
["O'", 'point', 'Intersect(h_3, e)', None, 2, False, True, None]
['g_2', 'numeric', "Distance[P, O'] / Distance[C, O']", None, None, None, None, None]
['g_1', 'numeric', "Distance[A, O'] / Distance[P, O']", None, None, None, None, None]
['t5', 'polygon', None, None, 2, False, False, None]
['i_3', 'segment', 'Segment(P, C, t5)', None, 2, False, False, True]
['p_4', 'segment', "Segment(C, O', t5)", '$a$', 2, False, True, True]
['c_6', 'segment', "Segment(O', P, t5)", '$b$', 2, False, True, True]
['t6', 'polygon', None, None, 2, False, False, None]
['j_3', 'segment', 'Segment(A, P, t6)', None, 2, False, False, True]
['a_5', 'segment', "Segment(P, O', t6)", None, 2, False, False, True]
['p_5', 'segment', "Segment(O', A, t6)", '$c$', 2, False, True, True]
['g_3', 'numeric', '((Area[t5] * g_2) * g_2)', None, None, None, None, None]
['text2', 'text', '"2. \xa0Geometric \xa0mean"', None, 9, False, False, None]
['ζ', 'angle', "Angle(P, O', C)", None, 2, False, False, None]
['d_3', 'conic', "Circle(O', C)", None, 2, False, False, True]
['A_1', 'point', 'Intersect(d_3, h_3, 1)', None, 2, False, True, True]
['k_3', 'line', 'Line(A_1, e)', None, 2, False, False, True]
['r_3', 'line', 'PerpendicularLine(A, k_3)', None, 2, False, False, None]
['poly8', 'polygon', None, None, 2, False, False, None]
['m_3', 'segment', "Segment(O', P, poly8)", None, 2, False, False, True]
['t_3', 'segment', 'Segment(P, H_1, poly8)', None, 2, False, False, True]
['f_4', 'segment', 'Segment(H_1, I_1, poly8)', None, 2, False, False, True]
['h_4', 'segment', "Segment(I_1, O', poly8)", None, 2, False, False, True]
['H_1', 'point', None, None, 2, False, True, True]
['I_1', 'point', None, None, 2, False, True, True]
['l_3', 'line', 'Line(A_1, e)', None, 2, False, False, True]
['B_1', 'point', 'Intersect(l_3, Line(P, A))', None, 2, False, True, True]
['C_1', 'point', 'Intersect(l_3, r_3)', None, 2, False, True, True]
['q1', 'polygon', None, None, 2, False, False, None]
['a_6', 'segment', "Segment(A, O', q1)", None, 2, False, False, True]
["o'", 'segment', "Segment(O', A_1, q1)", None, 2, False, False, True]
['n_3', 'segment', 'Segment(A_1, C_1, q1)', None, 2, False, False, True]
['q_3', 'segment', 'Segment(C_1, A, q1)', None, 2, False, False, True]
['t7', 'polygon', None, None, 2, False, False, None]
['s_3', 'segment', 'Segment(A, F, t7)', None, 2, False, False, True]
['a_7', 'segment', 'Segment(F, I_1, t7)', None, 2, False, False, True]
['f_5', 'segment', 'Segment(I_1, A, t7)', None, 2, False, False, True]
['t8', 'polygon', None, None, 2, False, False, None]
['b_3', 'segment', 'Segment(P, B_1, t8)', None, 2, False, False, True]
['p_6', 'segment', 'Segment(B_1, A_1, t8)', None, 2, False, False, True]
['e_3', 'segment', 'Segment(A_1, P, t8)', None, 2, False, False, True]
['text5_{3}', 'text', '"$proj_{\\vec{a}}\\ \\vec{b} = \\frac{\\vec{b}\\cdot\\vec{a}}{\\vec{a}\\cdot\\vec{a}}\\ \\vec{a}$"', None, 9, False, False, None]
['η', 'angle', 'Angle(C, A, B)', '$\\pi - \\theta$', 6, False, True, None]

## Construction Protocol

In [73]:
ggb.parser.parse()

AttributeError: 'ggb_parser' object has no attribute 'parse'

In [21]:
ggb.parser.command_cache.get_all()

{'Angle': 8,
 'Area': 1,
 'Circle': 59,
 'Distance': 5,
 'Intersect': 110,
 'Line': 109,
 'Midpoint': 21,
 'PerpendicularLine': 98,
 'Point': 42,
 'Polygon': 153,
 'Ray': 84,
 'Segment': 229,
 'Translate': 3,
 'Vector': 64,
 'cos': 2,
 'sin²': 2}

In [74]:
p.parse()

In [75]:
nx.write_network_text(p.G)

╟── C
╎   ├─╼ poly1 ╾ A
╎   │   ├─╼ f ╾ C, A
╎   │   ├─╼ g ╾ A, E
╎   │   ├─╼ h ╾ E, D
╎   │   └─╼ i ╾ D, C
╎   ├─╼ E ╾ A
╎   │   ├─╼ l ╾ k
╎   │   │   └─╼ q ╾ A
╎   │   ├─╼ p ╾ m
╎   │   │   └─╼ V ╾ n
╎   │   │       ├─╼ poly7 ╾ M
╎   │   │       │   ├─╼ d_2 ╾ V, M
╎   │   │       │   ├─╼ e_2 ╾ M, W
╎   │   │       │   ├─╼ f_3 ╾ W, Z
╎   │   │       │   └─╼ g_{6} ╾ Z, V
╎   │   │       ├─╼ W ╾ M
╎   │   │       │   └─╼  ...
╎   │   │       ├─╼ Z ╾ M
╎   │   │       │   └─╼  ...
╎   │   │       └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ D ╾ A
╎   │   ├─╼ m ╾ j
╎   │   │   └─╼  ...
╎   │   ├─╼ n ╾ j
╎   │   │   └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ O ╾ A
╎   │   ├─╼ c_1 ╾ C
╎   │   │   ├─╼ P
╎   │   │   │   ├─╼ j ╾ C
╎   │   │   │   │   ├─╼ B ╾ d
╎   │   │   │   │   │   ├─╼ w ╾ C
╎   │   │   │   │   │   │   ├─╼ u_1 ╾ u, C
╎   │   │   │   │   │   │   └─╼ v_1 ╾ v, P'
╎   │   │   │   │   │   ├─╼ h_1 ╾ e
╎   │   │   │   │   │   │   └─╼ L ╾ e
╎   │   │   │   │   │   │       ├─╼ t_1 ╾ C
╎   │   │   │   │   │   │       └─╼ d_1 ╾ A
╎   │   │   │   │   │   ├─╼ f_2 ╾ P
╎   │   │   │   │   │   ├─╼ g_{5} ╾ P'
╎   │   │   │   │   │   ├─╼ poly5 ╾ C
╎   │   │   │   │   │   │   ├─╼ i_2 ╾ C, B
╎   │   │   │   │   │   │   ├─╼ j_2 ╾ B, R
╎   │   │   │   │   │   │   ├─╼ k_2 ╾ R, S
╎   │   │   │   │   │   │   └─╼ l_2 ╾ S, C
╎   │   │   │   │   │   ├─╼ R ╾ C
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ S ╾ C
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ poly6 ╾ A
╎   │   │   │   │   │   │   ├─╼ m_2 ╾ B, A
╎   │   │   │   │   │   │   ├─╼ n_2 ╾ A, T
╎   │   │   │   │   │   │   ├─╼ q_2 ╾ T, U
╎   │   │   │   │   │   │   └─╼ r_2 ╾ U, B
╎   │   │   │   │   │   ├─╼ T ╾ A
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ U ╾ A
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ t4 ╾ A, C
╎   │   │   │   │   │   │   ├─╼ c_2 ╾ A, B
╎   │   │   │   │   │   │   ├─╼ a_4 ╾ B, C
╎   │   │   │   │   │   │   └─╼ b_2 ╾ C, A
╎   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ k ╾ A
╎   │   │   │   │   ├─╼ r ╾ C
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ i_1 ╾ O
╎   │   │   │   ├─╼ t1 ╾ O, C
╎   │   │   │   │   ├─╼ p_1 ╾ O, C
╎   │   │   │   │   ├─╼ o ╾ C, P
╎   │   │   │   │   └─╼ c_3 ╾ P, O
╎   │   │   │   ├─╼ t2 ╾ O, A
╎   │   │   │   │   ├─╼ p_2 ╾ O, A
╎   │   │   │   │   ├─╼ o_1 ╾ A, P
╎   │   │   │   │   └─╼ a_1 ╾ P, O
╎   │   │   │   ├─╼ t3 ╾ A, C
╎   │   │   │   │   ├─╼ p_3 ╾ A, C
╎   │   │   │   │   ├─╼ a_2 ╾ C, P
╎   │   │   │   │   └─╼ c_4 ╾ P, A
╎   │   │   │   ├─╼ poly3 ╾ C
╎   │   │   │   │   ├─╼ j_1 ╾ C, P
╎   │   │   │   │   ├─╼ k_1 ╾ P, F
╎   │   │   │   │   ├─╼ l_1 ╾ F, M
╎   │   │   │   │   └─╼ m_1 ╾ M, C
╎   │   │   │   ├─╼ F ╾ C
╎   │   │   │   │   ├─╼ t7 ╾ A, I_1
╎   │   │   │   │   │   ├─╼ s_3 ╾ A, F
╎   │   │   │   │   │   ├─╼ a_7 ╾ F, I_1
╎   │   │   │   │   │   └─╼ f_5 ╾ I_1, A
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ M ╾ C
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ poly4 ╾ A
╎   │   │   │   │   ├─╼ n_1 ╾ P, A
╎   │   │   │   │   ├─╼ q_1 ╾ A, N
╎   │   │   │   │   ├─╼ r_1 ╾ N, Q
╎   │   │   │   │   └─╼ s_1 ╾ Q, P
╎   │   │   │   ├─╼ N ╾ A
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ Q ╾ A
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ e_1 ╾ C
╎   │   │   │   ├─╼ h_3 ╾ e
╎   │   │   │   │   ├─╼ O' ╾ e
╎   │   │   │   │   │   ├─╼ t5 ╾ P, C
╎   │   │   │   │   │   │   ├─╼ i_3 ╾ P, C
╎   │   │   │   │   │   │   ├─╼ p_4 ╾ C, O'
╎   │   │   │   │   │   │   └─╼ c_6 ╾ O', P
╎   │   │   │   │   │   ├─╼ t6 ╾ A, P
╎   │   │   │   │   │   │   ├─╼ j_3 ╾ A, P
╎   │   │   │   │   │   │   ├─╼ a_5 ╾ P, O'
╎   │   │   │   │   │   │   └─╼ p_5 ╾ O', A
╎   │   │   │   │   │   ├─╼ d_3 ╾ C
╎   │   │   │   │   │   │   └─╼ A_1 ╾ h_3
╎   │   │   │   │   │   │       ├─╼ k_3 ╾ e
╎   │   │   │   │   │   │       │   └─╼ r_3 ╾ A
╎   │   │   │   │   │   │       │       └─╼ C_1 ╾ l_3
╎   │   │   │   │   │   │       │           ├─╼ q1 ╾ A, O', A_1
╎   │   │   │   │   │   │       │           │   ├─╼ a_6 ╾ A, O'
╎   │   │   │   │   │   │       │           │   ├─╼ o' ╾ O', A_1
╎   │   │   │   │   │   │       │           │   ├─╼ n_3 ╾ A_1, C_1
╎   │   │   │   │   │   │       │           │   └─╼ q_3 ╾ C_1, A
╎   │   │   │   │   │   │       │           └─╼  ...
╎   │   │   │   │   │   │       ├─╼ l_3 ╾ e
╎   │   │   │   │   │   │       │   ├─╼ B_1 ╾ P, A
╎   │   │   │   │   │   │       │   │   ├─╼ t8 ╾ P, A_1
╎   │   │   │   │   │   │       │   │   │   ├─╼ b_3 ╾ P, B_1
╎   │   │   │   │   │   │       │   │   │   ├─╼ p_6 ╾ B_1, A_1
╎   │   │   │   │   │   │       │   │   │   └─╼ e_3 ╾ A_1, P
╎   │   │   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │   │   │       │   └─╼  ...
╎   │   │   │   │   │   │       └─╼  ...
╎   │   │   │   │   │   ├─╼ poly8 ╾ P
╎   │   │   │   │   │   │   ├─╼ m_3 ╾ O', P
╎   │   │   │   │   │   │   ├─╼ t_3 ╾ P, H_1
╎   │   │   │   │   │   │   ├─╼ f_4 ╾ H_1, I_1
╎   │   │   │   │   │   │   └─╼ h_4 ╾ I_1, O'
╎   │   │   │   │   │   ├─╼ H_1 ╾ P
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ I_1 ╾ P
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   └─╼  ...
╎   │   │   │   └─╼  ...
╎   │   │   └─╼ P'
╎   │   │       ├─╼ d ╾ A
╎   │   │       │   ├─╼ f_1 ╾ C
╎   │   │       │   │   ├─╼ J ╾ c_{5}
╎   │   │       │   │   └─╼ K ╾ c_{5}
╎   │   │       │   │       └─╼ v ╾ C
╎   │   │       │   │           ├─╼ w' ╾ Γ_{uu}, u, Γ'_{uu}, C
╎   │   │       │   │           └─╼  ...
╎   │   │       │   ├─╼ g_{4} ╾ C
╎   │   │       │   └─╼  ...
╎   │   │       ├─╼ h_2 ╾ A
╎   │   │       └─╼  ...
╎   │   ├─╼ s_2 ╾ C
╎   │   ├─╼ t_2 ╾ A
╎   │   └─╼  ...
╎   ├─╼ poly2 ╾ A
╎   │   ├─╼ s ╾ A, C
╎   │   ├─╼ t ╾ C, G
╎   │   ├─╼ a_{3} ╾ G, H
╎   │   └─╼ b_1 ╾ H, A
╎   ├─╼ G ╾ A
╎   │   └─╼  ...
╎   ├─╼ H ╾ A
╎   │   └─╼  ...
╎   ├─╼ e ╾ A
╎   │   ├─╼ I ╾ c_{5}
╎   │   │   └─╼ u ╾ C
╎   │   │       └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ c_{5}
╎   │   └─╼  ...
╎   └─╼  ...
╟── A
╎   └─╼  ...
╟── Γ_{uu}
╎   └─╼  ...
╙── Γ'_{uu}
    └─╼  ...

In [76]:
p.parse_subgraph()

found: 'C' => 'c_{5}'
found: 'C', 'A' => 'e'
found: 'C', 'A' => 'E'
found: 'C', 'A' => 'D'
found: 'C', 'A' => 'O'
found: 'O' => 'c_1'
found: 'c_{5}', 'e' => 'I'
found: 'c_1' => 'P''
found: 'c_1' => 'P'
found: 'P'' => 'd'
found: 'P' => 'j'
found: 'P' => 'F'
found: 'P' => 'k'
found: 'P' => 'h_3'
found: 'P' => 'M'
found: 'j' => 'm'
found: 'j' => 'n'
found: 'h_3' => 'O''
found: 'd' => 'f_1'
found: 'd', 'j' => 'B'
found: 'f_1' => 'K'
found: 'O'' => 'I_1'
found: 'O'' => 'd_3'
found: 'B' => 'h_1'
found: 'm' => 'p'
found: 'd_3' => 'A_1'
found: 'p' => 'V'
found: 'A_1' => 'k_3'
found: 'A_1' => 'l_3'
found: 'k_3' => 'r_3'
found: 'l_3' => 'B_1'
found: 'r_3' => 'C_1'

In [77]:
nx.write_network_text(p.G2)

╟── C
╎   ├─╼ c_{5}
╎   │   └─╼ I ╾ e
╎   ├─╼ e ╾ A
╎   │   └─╼  ...
╎   ├─╼ E ╾ A
╎   ├─╼ D ╾ A
╎   └─╼ O ╾ A
╎       └─╼ c_1
╎           ├─╼ P'
╎           │   └─╼ d
╎           │       ├─╼ f_1
╎           │       │   └─╼ K
╎           │       └─╼ B ╾ j
╎           │           └─╼ h_1
╎           └─╼ P
╎               ├─╼ j
╎               │   ├─╼ m
╎               │   │   └─╼ p
╎               │   │       └─╼ V
╎               │   ├─╼ n
╎               │   └─╼  ...
╎               ├─╼ F
╎               ├─╼ k
╎               ├─╼ h_3
╎               │   └─╼ O'
╎               │       ├─╼ I_1
╎               │       └─╼ d_3
╎               │           └─╼ A_1
╎               │               ├─╼ k_3
╎               │               │   └─╼ r_3
╎               │               │       └─╼ C_1
╎               │               └─╼ l_3
╎               │                   └─╼ B_1
╎               └─╼ M
╙── A
    └─╼  ...

In [24]:
labels_map = {}
for n in p.ft:
    if n in p.G2:
        labels_map[n] = f"[{n}: {len(nx.descendants(p.G, n))}]"

In [25]:
nx.set_node_attributes(p.G, labels_map, "label")
nx.write_network_text(p.G, with_labels="label")

╟── [C: 141]
╎   ├─╼ poly1 ╾ [A: 140]
╎   │   ├─╼ f ╾ [C: 141], [A: 140]
╎   │   ├─╼ g ╾ [A: 140], [E: 13]
╎   │   ├─╼ h ╾ [E: 13], [D: 13]
╎   │   └─╼ i ╾ [D: 13], [C: 141]
╎   ├─╼ [E: 13] ╾ [A: 140]
╎   │   ├─╼ l ╾ [k: 3]
╎   │   │   └─╼ q ╾ [A: 140]
╎   │   ├─╼ [p: 8] ╾ [m: 9]
╎   │   │   └─╼ [V: 7] ╾ [n: 8]
╎   │   │       ├─╼ poly7 ╾ [M: 9]
╎   │   │       │   ├─╼ d_2 ╾ [V: 7], [M: 9]
╎   │   │       │   ├─╼ e_2 ╾ [M: 9], W
╎   │   │       │   ├─╼ f_3 ╾ W, Z
╎   │   │       │   └─╼ g_{6} ╾ Z, [V: 7]
╎   │   │       ├─╼ W ╾ [M: 9]
╎   │   │       │   └─╼  ...
╎   │   │       ├─╼ Z ╾ [M: 9]
╎   │   │       │   └─╼  ...
╎   │   │       └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ [D: 13] ╾ [A: 140]
╎   │   ├─╼ [m: 9] ╾ [j: 39]
╎   │   │   └─╼  ...
╎   │   ├─╼ [n: 8] ╾ [j: 39]
╎   │   │   └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ [O: 122] ╾ [A: 140]
╎   │   ├─╼ [c_1: 119] ╾ [C: 141]
╎   │   │   ├─╼ [P: 109]
╎   │   │   │   ├─╼ [j: 39] ╾ [C: 141]
╎   │   │   │   │   ├─╼ [B: 27] ╾ [d: 34]
╎   │   │   │   │   │   ├─╼ w ╾ [C: 141]
╎   │   │   │   │   │   │   ├─╼ u_1 ╾ u, [C: 141]
╎   │   │   │   │   │   │   └─╼ v_1 ╾ v, [P': 36]
╎   │   │   │   │   │   ├─╼ [h_1: 3] ╾ [e: 45]
╎   │   │   │   │   │   │   └─╼ L ╾ [e: 45]
╎   │   │   │   │   │   │       ├─╼ t_1 ╾ [C: 141]
╎   │   │   │   │   │   │       └─╼ d_1 ╾ [A: 140]
╎   │   │   │   │   │   ├─╼ f_2 ╾ [P: 109]
╎   │   │   │   │   │   ├─╼ g_{5} ╾ [P': 36]
╎   │   │   │   │   │   ├─╼ poly5 ╾ [C: 141]
╎   │   │   │   │   │   │   ├─╼ i_2 ╾ [C: 141], [B: 27]
╎   │   │   │   │   │   │   ├─╼ j_2 ╾ [B: 27], R
╎   │   │   │   │   │   │   ├─╼ k_2 ╾ R, S
╎   │   │   │   │   │   │   └─╼ l_2 ╾ S, [C: 141]
╎   │   │   │   │   │   ├─╼ R ╾ [C: 141]
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ S ╾ [C: 141]
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ poly6 ╾ [A: 140]
╎   │   │   │   │   │   │   ├─╼ m_2 ╾ [B: 27], [A: 140]
╎   │   │   │   │   │   │   ├─╼ n_2 ╾ [A: 140], T
╎   │   │   │   │   │   │   ├─╼ q_2 ╾ T, U
╎   │   │   │   │   │   │   └─╼ r_2 ╾ U, [B: 27]
╎   │   │   │   │   │   ├─╼ T ╾ [A: 140]
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ U ╾ [A: 140]
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ t4 ╾ [A: 140], [C: 141]
╎   │   │   │   │   │   │   ├─╼ c_2 ╾ [A: 140], [B: 27]
╎   │   │   │   │   │   │   ├─╼ a_4 ╾ [B: 27], [C: 141]
╎   │   │   │   │   │   │   └─╼ b_2 ╾ [C: 141], [A: 140]
╎   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ [k: 3] ╾ [A: 140]
╎   │   │   │   │   ├─╼ r ╾ [C: 141]
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ i_1 ╾ [O: 122]
╎   │   │   │   ├─╼ t1 ╾ [O: 122], [C: 141]
╎   │   │   │   │   ├─╼ p_1 ╾ [O: 122], [C: 141]
╎   │   │   │   │   ├─╼ o ╾ [C: 141], [P: 109]
╎   │   │   │   │   └─╼ c_3 ╾ [P: 109], [O: 122]
╎   │   │   │   ├─╼ t2 ╾ [O: 122], [A: 140]
╎   │   │   │   │   ├─╼ p_2 ╾ [O: 122], [A: 140]
╎   │   │   │   │   ├─╼ o_1 ╾ [A: 140], [P: 109]
╎   │   │   │   │   └─╼ a_1 ╾ [P: 109], [O: 122]
╎   │   │   │   ├─╼ t3 ╾ [A: 140], [C: 141]
╎   │   │   │   │   ├─╼ p_3 ╾ [A: 140], [C: 141]
╎   │   │   │   │   ├─╼ a_2 ╾ [C: 141], [P: 109]
╎   │   │   │   │   └─╼ c_4 ╾ [P: 109], [A: 140]
╎   │   │   │   ├─╼ poly3 ╾ [C: 141]
╎   │   │   │   │   ├─╼ j_1 ╾ [C: 141], [P: 109]
╎   │   │   │   │   ├─╼ k_1 ╾ [P: 109], [F: 6]
╎   │   │   │   │   ├─╼ l_1 ╾ [F: 6], [M: 9]
╎   │   │   │   │   └─╼ m_1 ╾ [M: 9], [C: 141]
╎   │   │   │   ├─╼ [F: 6] ╾ [C: 141]
╎   │   │   │   │   ├─╼ t7 ╾ [A: 140], [I_1: 6]
╎   │   │   │   │   │   ├─╼ s_3 ╾ [A: 140], [F: 6]
╎   │   │   │   │   │   ├─╼ a_7 ╾ [F: 6], [I_1: 6]
╎   │   │   │   │   │   └─╼ f_5 ╾ [I_1: 6], [A: 140]
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ [M: 9] ╾ [C: 141]
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ poly4 ╾ [A: 140]
╎   │   │   │   │   ├─╼ n_1 ╾ [P: 109], [A: 140]
╎   │   │   │   │   ├─╼ q_1 ╾ [A: 140], N
╎   │   │   │   │   ├─╼ r_1 ╾ N, Q
╎   │   │   │   │   └─╼ s_1 ╾ Q, [P: 109]
╎   │   │   │   ├─╼ N ╾ [A: 140]
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ Q ╾ [A: 140]
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ e_1 ╾ [C: 141]
╎   │   │   │   ├─╼ [h_3: 36] ╾ [e: 45]
╎   │   │   │   │   ├─╼ [O': 35] ╾ [e: 45]
╎   │   │   │   │   │   ├─╼ t5 ╾ [P: 109], [C: 141]
╎   │   │   │   │   │   │   ├─╼ i_3 ╾ [P: 109], [C: 141]
╎   │   │   │   │   │   │   ├─╼ p_4 ╾ [C: 141], [O': 35]
╎   │   │   │   │   │   │   └─╼ c_6 ╾ [O': 35], [P: 109]
╎   │   │   │   │   │   ├─╼ t6 ╾ [A: 140], [P: 109]
╎   │   │   │   │   │   │   ├─╼ j_3 ╾ [A: 140], [P: 109]
╎   │   │   │   │   │   │   ├─╼ a_5 ╾ [P: 109], [O': 35]
╎   │   │   │   │   │   │   └─╼ p_5 ╾ [O': 35], [A: 140]
╎   │   │   │   │   │   ├─╼ [d_3: 15] ╾ [C: 141]
╎   │   │   │   │   │   │   └─╼ [A_1: 14] ╾ [h_3: 36]
╎   │   │   │   │   │   │       ├─╼ [k_3: 7] ╾ [e: 45]
╎   │   │   │   │   │   │       │   └─╼ [r_3: 6] ╾ [A: 140]
╎   │   │   │   │   │   │       │       └─╼ [C_1: 5] ╾ [l_3: 11]
╎   │   │   │   │   │   │       │           ├─╼ q1 ╾ [A: 140], [O': 35], [A_1: 14]
╎   │   │   │   │   │   │       │           │   ├─╼ a_6 ╾ [A: 140], [O': 35]
╎   │   │   │   │   │   │       │           │   ├─╼ o' ╾ [O': 35], [A_1: 14]
╎   │   │   │   │   │   │       │           │   ├─╼ n_3 ╾ [A_1: 14], [C_1: 5]
╎   │   │   │   │   │   │       │           │   └─╼ q_3 ╾ [C_1: 5], [A: 140]
╎   │   │   │   │   │   │       │           └─╼  ...
╎   │   │   │   │   │   │       ├─╼ [l_3: 11] ╾ [e: 45]
╎   │   │   │   │   │   │       │   ├─╼ [B_1: 4] ╾ [P: 109], [A: 140]
╎   │   │   │   │   │   │       │   │   ├─╼ t8 ╾ [P: 109], [A_1: 14]
╎   │   │   │   │   │   │       │   │   │   ├─╼ b_3 ╾ [P: 109], [B_1: 4]
╎   │   │   │   │   │   │       │   │   │   ├─╼ p_6 ╾ [B_1: 4], [A_1: 14]
╎   │   │   │   │   │   │       │   │   │   └─╼ e_3 ╾ [A_1: 14], [P: 109]
╎   │   │   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │   │   │       │   └─╼  ...
╎   │   │   │   │   │   │       └─╼  ...
╎   │   │   │   │   │   ├─╼ poly8 ╾ [P: 109]
╎   │   │   │   │   │   │   ├─╼ m_3 ╾ [O': 35], [P: 109]
╎   │   │   │   │   │   │   ├─╼ t_3 ╾ [P: 109], H_1
╎   │   │   │   │   │   │   ├─╼ f_4 ╾ H_1, [I_1: 6]
╎   │   │   │   │   │   │   └─╼ h_4 ╾ [I_1: 6], [O': 35]
╎   │   │   │   │   │   ├─╼ H_1 ╾ [P: 109]
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   ├─╼ [I_1: 6] ╾ [P: 109]
╎   │   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   │   └─╼  ...
╎   │   │   │   │   └─╼  ...
╎   │   │   │   └─╼  ...
╎   │   │   └─╼ [P': 36]
╎   │   │       ├─╼ [d: 34] ╾ [A: 140]
╎   │   │       │   ├─╼ [f_1: 5] ╾ [C: 141]
╎   │   │       │   │   ├─╼ J ╾ [c_{5}: 8]
╎   │   │       │   │   └─╼ [K: 3] ╾ [c_{5}: 8]
╎   │   │       │   │       └─╼ v ╾ [C: 141]
╎   │   │       │   │           ├─╼ w' ╾ Γ_{uu}, u, Γ'_{uu}, [C: 141]
╎   │   │       │   │           └─╼  ...
╎   │   │       │   ├─╼ g_{4} ╾ [C: 141]
╎   │   │       │   └─╼  ...
╎   │   │       ├─╼ h_2 ╾ [A: 140]
╎   │   │       └─╼  ...
╎   │   ├─╼ s_2 ╾ [C: 141]
╎   │   ├─╼ t_2 ╾ [A: 140]
╎   │   └─╼  ...
╎   ├─╼ poly2 ╾ [A: 140]
╎   │   ├─╼ s ╾ [A: 140], [C: 141]
╎   │   ├─╼ t ╾ [C: 141], G
╎   │   ├─╼ a_{3} ╾ G, H
╎   │   └─╼ b_1 ╾ H, [A: 140]
╎   ├─╼ G ╾ [A: 140]
╎   │   └─╼  ...
╎   ├─╼ H ╾ [A: 140]
╎   │   └─╼  ...
╎   ├─╼ [e: 45] ╾ [A: 140]
╎   │   ├─╼ [I: 3] ╾ [c_{5}: 8]
╎   │   │   └─╼ u ╾ [C: 141]
╎   │   │       └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ [c_{5}: 8]
╎   │   └─╼  ...
╎   └─╼  ...
╟── [A: 140]
╎   └─╼  ...
╟── Γ_{uu}
╎   └─╼  ...
╙── Γ'_{uu}
    └─╼  ...